<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Currency::truncate();
        Schema::enableForeignKeyConstraints();

        $currencies = [
            ['Albanian lek', 'ALL', 'Lek', 1],
            ['Armenian dram', 'AMD', '֏', 1],
            ['Netherlands Antillean guilder', 'ANG', 'ƒ', 1],
            ['Angolan kwanza', 'AOA', 'Kz', 1],
            ['Argentine peso', 'ARS', '$', 1],
            ['Australian dollar', 'AUD', '$', 1],
            ['Aruban florin', 'AWG', 'ƒ', 1],
            ['Azerbaijani manat', 'AZN', 'm', 1],
            ['Bosnia and Herzegovina convertible mark', 'BAM', 'KM', 1],
            ['Barbadian dollar', 'BBD', 'Bds$', 1],
            ['Bangladeshi taka', 'BDT', '৳', 1],
            ['Bulgarian lev', 'BGN', 'Лв.', 1],
            ['Bahraini dinar', 'BHD', '.د.ب', 1],
            ['Burundian franc', 'BIF', 'FBu', 1],
            ['Bermudian dollar', 'BMD', '$', 1],
            ['Brunei dollar', 'BND', 'B$', 1],
            ['Bolivian boliviano', 'BOB', 'Bs.', 1],
            ['Brazilian real', 'BRL', 'R$', 1],
            ['Bahamian dollar', 'BSD', 'B$', 1],
            ['Bhutanese ngultrum', 'BTN', 'Nu.', 1],
            ['Botswana pula', 'BWP', 'P', 1],
            ['Belarusian ruble', 'BYN', 'Br', 1],
            ['Belize dollar', 'BZD', '$', 1],
            ['Canadian dollar', 'CAD', '$', 1],
            ['Congolese Franc', 'CDF', 'FC', 1],
            ['Swiss franc', 'CHF', 'CHf', 1],
            ['Chilean peso', 'CLP', '$', 1],
            ['Chinese yuan', 'CNY', '¥', 1],
            ['Colombian peso', 'COP', '$', 1],
            ['Costa Rican colÃ³n', 'CRC', '₡', 1],
            ['Cuban peso', 'CUP', '$', 1],
            ['Cape Verdean escudo', 'CVE', '$', 1],
            ['Czech koruna', 'CZK', 'Kč', 1],
            ['Djiboutian franc', 'DJF', 'Fdj', 1],
            ['Danish krone', 'DKK', 'Kr.', 1],
            ['Dominican peso', 'DOP', '$', 1],
            ['Algerian dinar', 'DZD', 'دج', 1],
            ['Egyptian pound', 'EGP', 'ج.م', 1],
            ['Eritrean nakfa', 'ERN', 'Nfk', 1],
            ['Ethiopian birr', 'ETB', 'Nkf', 1],
            ['Euro', 'EUR', '€', 1],
            ['Fijian dollar', 'FJD', 'FJ$', 1],
            ['Falkland Islands pound', 'FKP', '£', 1],
            ['British pound', 'GBP', '£', 1],
            ['Georgian lari', 'GEL', 'ლ', 1],
            ['Ghanaian cedi', 'GHS', 'GH₵', 1],
            ['Gibraltar pound', 'GIP', '£', 1],
            ['Gambian dalasi', 'GMD', 'D', 1],
            ['Guinean franc', 'GNF', 'FG', 1],
            ['Guatemalan quetzal', 'GTQ', 'Q', 1],
            ['Guyanese dollar', 'GYD', '$', 1],
            ['Hong Kong dollar', 'HKD', '$', 1],
            ['Honduran lempira', 'HNL', 'L', 1],
            ['Haitian gourde', 'HTG', 'G', 1],
            ['Hungarian forint', 'HUF', 'Ft', 1],
            ['Indonesian rupiah', 'IDR', 'Rp', 1],
            ['Israeli new shekel', 'ILS', '₪', 1],
            ['Israeli new shekel', 'ILS', '₪', 1],
            ['Indian rupee', 'INR', '₹', 1],
            ['Iraqi dinar', 'IQD', 'د.ع', 1],
            ['Iranian rial', 'IRR', '﷼', 1],
            ['Icelandic krÃ³na', 'ISK', 'ko', 1],
            ['Jamaican dollar', 'JMD', 'J$', 1],
            ['Jordanian dinar', 'JOD', 'ا.د', 1],
            ['Japanese yen', 'JPY', '¥', 1],
            ['Kenyan shilling', 'KES', 'KSh', 1],
            ['Kyrgyzstani som', 'KGS', 'лв', 1],
            ['Cambodian riel', 'KHR', 'KHR', 1],
            ['Comorian franc', 'KMF', 'CF', 1],
            ['North Korean Won', 'KPW', '₩', 1],
            ['Won', 'KRW', '₩', 1],
            ['Kuwaiti dinar', 'KWD', 'ك.د', 1],
            ['Cayman Islands dollar', 'KYD', '$', 1],
            ['Kazakhstani tenge', 'KZT', 'лв', 1],
            ['Lao kip', 'LAK', '₭', 1],
            ['Lebanese pound', 'LBP', '£', 1],
            ['Sri Lankan rupee', 'LKR', 'Rs', 1],
            ['Liberian dollar', 'LRD', '$', 1],
            ['Lesotho loti', 'LSL', 'L', 1],
            ['Libyan dinar', 'LYD', 'د.ل', 1],
            ['Moroccan dirham', 'MAD', 'DH', 1],
            ['Moldovan leu', 'MDL', 'L', 1],
            ['Malagasy ariary', 'MGA', 'Ar', 1],
            ['Denar', 'MKD', 'ден', 1],
            ['Burmese kyat', 'MMK', 'K', 1],
            ['Mongolian tÃ¶grÃ¶g', 'MNT', '₮', 1],
            ['Macanese pataca', 'MOP', '$', 1],
            ['Mauritanian ouguiya', 'MRU', 'UM', 1],
            ['Mauritian rupee', 'MUR', '₨', 1],
            ['Maldivian rufiyaa', 'MVR', 'Rf', 1],
            ['Malawian kwacha', 'MWK', 'MK', 1],
            ['Mexican peso', 'MXN', '$', 1],
            ['Malaysian ringgit', 'MYR', 'RM', 1],
            ['Mozambican metical', 'MZN', 'MT', 1],
            ['Namibian dollar', 'NAD', '$', 1],
            ['Nigerian naira', 'NGN', '₦', 1],
            ['Nicaraguan cÃ³rdoba', 'NIO', 'C$', 1],
            ['Norwegian krone', 'NOK', 'ko', 1],
            ['Nepalese rupee', 'NPR', '₨', 1],
            ['New Zealand dollar', 'NZD', '$', 1],
            ['Omani rial', 'OMR', '.ع.ر', 1],
            ['Panamanian balboa', 'PAB', 'B/.', 1],
            ['Peruvian sol', 'PEN', 'S/.', 1],
            ['Papua New Guinean kina', 'PGK', 'K', 1],
            ['Philippine peso', 'PHP', '₱', 1],
            ['Pakistani rupee', 'PKR', '₨', 1],
            ['Polish zÅ‚oty', 'PLN', 'zł', 1],
            ['Paraguayan guarani', 'PYG', '₲', 1],
            ['Qatari riyal', 'QAR', 'ق.ر', 1],
            ['Romanian leu', 'RON', 'lei', 1],
            ['Serbian dinar', 'RSD', 'din', 1],
            ['Russian ruble', 'RUB', '₽', 1],
            ['Rwandan franc', 'RWF', 'FRw', 1],
            ['Saudi riyal', 'SAR', '﷼', 1],
            ['Solomon Islands dollar', 'SBD', 'Si$', 1],
            ['Seychellois rupee', 'SCR', 'SRe', 1],
            ['Sudanese pound', 'SDG', '.س.ج', 1],
            ['Swedish krona', 'SEK', 'ko', 1],
            ['Singapore dollar', 'SGD', '$', 1],
            ['Saint Helena pound', 'SHP', '£', 1],
            ['Sierra Leonean leone', 'SLL', 'Le', 1],
            ['Somali shilling', 'SOS', 'Sh.so.', 1],
            ['Surinamese dollar', 'SRD', '$', 1],
            ['South Sudanese pound', 'SSP', '£', 1],
            ['Dobra', 'STN', 'Db', 1],
            ['Syrian pound', 'SYP', 'LS', 1],
            ['Lilangeni', 'SZL', 'E', 1],
            ['Thai baht', 'THB', '฿', 1],
            ['Tajikistani somoni', 'TJS', 'SM', 1],
            ['Turkmenistan manat', 'TMT', 'T', 1],
            ['Tunisian dinar', 'TND', 'ت.د', 1],
            ['Tongan paÊ»anga', 'TOP', '$', 1],
            ['Turkish lira', 'TRY', '₺', 1],
            ['Trinidad and Tobago dollar', 'TTD', '$', 1],
            ['New Taiwan dollar', 'TWD', '$', 1],
            ['Tanzanian shilling', 'TZS', 'TSh', 1],
            ['Ukrainian hryvnia', 'UAH', '₴', 1],
            ['Ugandan shilling', 'UGX', 'USh', 1],
            ['United States dollar', 'USD', '$', 1],
            ['Uruguayan peso', 'UYU', '$', 1],
            ['Uzbekistani soÊ»m', 'UZS', 'лв', 1],
            ['BolÃ­var', 'VES', 'Bs', 1],
            ['Vietnamese Ä‘á»“ng', 'VND', '₫', 1],
            ['Vanuatu vatu', 'VUV', 'VT', 1],
            ['Samoan tÄlÄ', 'WST', 'SAT', 1],
            ['Central African CFA franc', 'XAF', 'FCFA', 1],
            ['Eastern Caribbean dollar', 'XCD', '$', 1],
            ['West African CFA franc', 'XOF', 'CFA', 1],
            ['CFP franc', 'XPF', '₣', 1],
            ['Yemeni rial', 'YER', '﷼', 1],
            ['South African rand', 'ZAR', 'R', 1],
            ['Zambian kwacha', 'ZMW', 'ZK', 1],
            ['Zimbabwe Dollar', 'ZWL', '$', 1]

        ];
        Currency::insert($currencies);
    }
}