<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Currency::truncate();
        Schema::enableForeignKeyConstraints();

        $currencies = [
            ['Albanian lek', 'ALL', 'Lek', true],
            ['Armenian dram', 'AMD', '֏', true],
            ['Netherlands Antillean guilder', 'ANG', 'ƒ', true],
            ['Angolan kwanza', 'AOA', 'Kz', true],
            ['Argentine peso', 'ARS', '$', true],
            ['Australian dollar', 'AUD', '$', true],
            ['Aruban florin', 'AWG', 'ƒ', true],
            ['Azerbaijani manat', 'AZN', 'm', true],
            ['Bosnia and Herzegovina convertible mark', 'BAM', 'KM', true],
            ['Barbadian dollar', 'BBD', 'Bds$', true],
            ['Bangladeshi taka', 'BDT', '৳', true],
            ['Bulgarian lev', 'BGN', 'Лв.', true],
            ['Bahraini dinar', 'BHD', '.د.ب', true],
            ['Burundian franc', 'BIF', 'FBu', true],
            ['Bermudian dollar', 'BMD', '$', true],
            ['Brunei dollar', 'BND', 'B$', true],
            ['Bolivian boliviano', 'BOB', 'Bs.', true],
            ['Brazilian real', 'BRL', 'R$', true],
            ['Bahamian dollar', 'BSD', 'B$', true],
            ['Bhutanese ngultrum', 'BTN', 'Nu.', true],
            ['Botswana pula', 'BWP', 'P', true],
            ['Belarusian ruble', 'BYN', 'Br', true],
            ['Belize dollar', 'BZD', '$', true],
            ['Canadian dollar', 'CAD', '$', true],
            ['Congolese Franc', 'CDF', 'FC', true],
            ['Swiss franc', 'CHF', 'CHf', true],
            ['Chilean peso', 'CLP', '$', true],
            ['Chinese yuan', 'CNY', '¥', true],
            ['Colombian peso', 'COP', '$', true],
            ['Costa Rican colÃ³n', 'CRC', '₡', true],
            ['Cuban peso', 'CUP', '$', true],
            ['Cape Verdean escudo', 'CVE', '$', true],
            ['Czech koruna', 'CZK', 'Kč', true],
            ['Djiboutian franc', 'DJF', 'Fdj', true],
            ['Danish krone', 'DKK', 'Kr.', true],
            ['Dominican peso', 'DOP', '$', true],
            ['Algerian dinar', 'DZD', 'دج', true],
            ['Egyptian pound', 'EGP', 'ج.م', true],
            ['Eritrean nakfa', 'ERN', 'Nfk', true],
            ['Ethiopian birr', 'ETB', 'Nkf', true],
            ['Euro', 'EUR', '€', true],
            ['Fijian dollar', 'FJD', 'FJ$', true],
            ['Falkland Islands pound', 'FKP', '£', true],
            ['British pound', 'GBP', '£', true],
            ['Georgian lari', 'GEL', 'ლ', true],
            ['Ghanaian cedi', 'GHS', 'GH₵', true],
            ['Gibraltar pound', 'GIP', '£', true],
            ['Gambian dalasi', 'GMD', 'D', true],
            ['Guinean franc', 'GNF', 'FG', true],
            ['Guatemalan quetzal', 'GTQ', 'Q', true],
            ['Guyanese dollar', 'GYD', '$', true],
            ['Hong Kong dollar', 'HKD', '$', true],
            ['Honduran lempira', 'HNL', 'L', true],
            ['Haitian gourde', 'HTG', 'G', true],
            ['Hungarian forint', 'HUF', 'Ft', true],
            ['Indonesian rupiah', 'IDR', 'Rp', true],
            ['Israeli new shekel', 'ILS', '₪', true],
            ['Israeli new shekel', 'ILS', '₪', true],
            ['Indian rupee', 'INR', '₹', true],
            ['Iraqi dinar', 'IQD', 'د.ع', true],
            ['Iranian rial', 'IRR', '﷼', true],
            ['Icelandic krÃ³na', 'ISK', 'ko', true],
            ['Jamaican dollar', 'JMD', 'J$', true],
            ['Jordanian dinar', 'JOD', 'ا.د', true],
            ['Japanese yen', 'JPY', '¥', true],
            ['Kenyan shilling', 'KES', 'KSh', true],
            ['Kyrgyzstani som', 'KGS', 'лв', true],
            ['Cambodian riel', 'KHR', 'KHR', true],
            ['Comorian franc', 'KMF', 'CF', true],
            ['North Korean Won', 'KPW', '₩', true],
            ['Won', 'KRW', '₩', true],
            ['Kuwaiti dinar', 'KWD', 'ك.د', true],
            ['Cayman Islands dollar', 'KYD', '$', true],
            ['Kazakhstani tenge', 'KZT', 'лв', true],
            ['Lao kip', 'LAK', '₭', true],
            ['Lebanese pound', 'LBP', '£', true],
            ['Sri Lankan rupee', 'LKR', 'Rs', true],
            ['Liberian dollar', 'LRD', '$', true],
            ['Lesotho loti', 'LSL', 'L', true],
            ['Libyan dinar', 'LYD', 'د.ل', true],
            ['Moroccan dirham', 'MAD', 'DH', true],
            ['Moldovan leu', 'MDL', 'L', true],
            ['Malagasy ariary', 'MGA', 'Ar', true],
            ['Denar', 'MKD', 'ден', true],
            ['Burmese kyat', 'MMK', 'K', true],
            ['Mongolian tÃ¶grÃ¶g', 'MNT', '₮', true],
            ['Macanese pataca', 'MOP', '$', true],
            ['Mauritanian ouguiya', 'MRU', 'UM', true],
            ['Mauritian rupee', 'MUR', '₨', true],
            ['Maldivian rufiyaa', 'MVR', 'Rf', true],
            ['Malawian kwacha', 'MWK', 'MK', true],
            ['Mexican peso', 'MXN', '$', true],
            ['Malaysian ringgit', 'MYR', 'RM', true],
            ['Mozambican metical', 'MZN', 'MT', true],
            ['Namibian dollar', 'NAD', '$', true],
            ['Nigerian naira', 'NGN', '₦', true],
            ['Nicaraguan cÃ³rdoba', 'NIO', 'C$', true],
            ['Norwegian krone', 'NOK', 'ko', true],
            ['Nepalese rupee', 'NPR', '₨', true],
            ['New Zealand dollar', 'NZD', '$', true],
            ['Omani rial', 'OMR', '.ع.ر', true],
            ['Panamanian balboa', 'PAB', 'B/.', true],
            ['Peruvian sol', 'PEN', 'S/.', true],
            ['Papua New Guinean kina', 'PGK', 'K', true],
            ['Philippine peso', 'PHP', '₱', true],
            ['Pakistani rupee', 'PKR', '₨', true],
            ['Polish zÅ‚oty', 'PLN', 'zł', true],
            ['Paraguayan guarani', 'PYG', '₲', true],
            ['Qatari riyal', 'QAR', 'ق.ر', true],
            ['Romanian leu', 'RON', 'lei', true],
            ['Serbian dinar', 'RSD', 'din', true],
            ['Russian ruble', 'RUB', '₽', true],
            ['Rwandan franc', 'RWF', 'FRw', true],
            ['Saudi riyal', 'SAR', '﷼', true],
            ['Solomon Islands dollar', 'SBD', 'Si$', true],
            ['Seychellois rupee', 'SCR', 'SRe', true],
            ['Sudanese pound', 'SDG', '.س.ج', true],
            ['Swedish krona', 'SEK', 'ko', true],
            ['Singapore dollar', 'SGD', '$', true],
            ['Saint Helena pound', 'SHP', '£', true],
            ['Sierra Leonean leone', 'SLL', 'Le', true],
            ['Somali shilling', 'SOS', 'Sh.so.', true],
            ['Surinamese dollar', 'SRD', '$', true],
            ['South Sudanese pound', 'SSP', '£', true],
            ['Dobra', 'STN', 'Db', true],
            ['Syrian pound', 'SYP', 'LS', true],
            ['Lilangeni', 'SZL', 'E', true],
            ['Thai baht', 'THB', '฿', true],
            ['Tajikistani somoni', 'TJS', 'SM', true],
            ['Turkmenistan manat', 'TMT', 'T', true],
            ['Tunisian dinar', 'TND', 'ت.د', true],
            ['Tongan paÊ»anga', 'TOP', '$', true],
            ['Turkish lira', 'TRY', '₺', true],
            ['Trinidad and Tobago dollar', 'TTD', '$', true],
            ['New Taiwan dollar', 'TWD', '$', true],
            ['Tanzanian shilling', 'TZS', 'TSh', true],
            ['Ukrainian hryvnia', 'UAH', '₴', true],
            ['Ugandan shilling', 'UGX', 'USh', true],
            ['United States dollar', 'USD', '$', true],
            ['Uruguayan peso', 'UYU', '$', true],
            ['Uzbekistani soÊ»m', 'UZS', 'лв', true],
            ['BolÃ­var', 'VES', 'Bs', true],
            ['Vietnamese Ä‘á»“ng', 'VND', '₫', true],
            ['Vanuatu vatu', 'VUV', 'VT', true],
            ['Samoan tÄlÄ', 'WST', 'SAT', true],
            ['Central African CFA franc', 'XAF', 'FCFA', true],
            ['Eastern Caribbean dollar', 'XCD', '$', true],
            ['West African CFA franc', 'XOF', 'CFA', true],
            ['CFP franc', 'XPF', '₣', true],
            ['Yemeni rial', 'YER', '﷼', true],
            ['South African rand', 'ZAR', 'R', true],
            ['Zambian kwacha', 'ZMW', 'ZK', true],
            ['Zimbabwe Dollar', 'ZWL', '$', true]
        ];

        foreach ($currencies as $currency) {
            Currency::updateOrCreate([
                'code' => $currency[1],
            ], [
                'name' => $currency[0],
                'symbol' => $currency[2],
                'is_active' => $currency[3],
            ]);
        }
    }
}