<?php

$basePath = __DIR__ . '/resources/lang/es';

if (!is_dir($basePath)) {
    die("Error: Spanish language directory not found at $basePath\n");
}

$es_translations = [
    'main.php' => [
        "create_new_user" => "Agregar Nuevo Usuario",
        "edit_user" => "Editar Usuario",
        "create_new_user_description" => "Crear una nueva cuenta de usuario en el sistema",
        "edit_user_description" => "Editar una cuenta de usuario existente en el sistema",
        "basic_user_info" => "Información Básica del Usuario",
        "user_avatar" => "Avatar del Usuario",
        "bio_placeholder" => "Ingrese la biografía del usuario...",
        "mobile_placeholder" => "Ingrese el número de móvil",
        "user_code_placeholder" => "Ingrese el código único de usuario",
        "employee_id_placeholder" => "Ingrese el ID de empleado",
        "department_placeholder" => "Ingrese el nombre del departamento",
        "position_placeholder" => "Ingrese el puesto de trabajo",
        "preferred_language" => "Idioma Preferido",
        "select_language" => "Seleccionar Idioma",
        "timezone_field" => "Zona Horaria",
        "preferences_placeholder" => "Ingrese las preferencias del usuario",
        "avatar" => "Avatar",
        "avatar_url" => "URL del Avatar",
        "avatar_url_placeholder" => "Ingrese la URL de la imagen del avatar",
        "password_changed_at" => "Contraseña Cambiada El",
        "force_password_change" => "Forzar Cambio de Contraseña",
        "last_login_at" => "Último Acceso El",
        "last_login_ip" => "Última IP de Acceso",
        "employment_information" => "Información de Empleo",
        "additional_information" => "Información Adicional",
        "additional_descriptions" => "Descripciones Adicionales",
        "user_creation_tips" => "Consejos para la Creación de Usuarios",
        "complete_profile" => "Completar Perfil",
        "secure_password" => "Contraseña Segura",
        "user_permissions" => "Permisos de Usuario",
        "user_permissions_desc" => "Establecer permisos y roles apropiados para la cuenta del usuario",
        "update_user" => "Actualizar Usuario",
        "back_to_users" => "Volver a Usuarios",
        "user_editing_tips" => "Consejos para la Edición de Usuarios",
        "password_optional" => "Contraseña Opcional",
        "keep_updated" => "Mantener Información Actualizada",
        "keep_updated_desc" => "Asegúrese de que la información del usuario esté actualizada para una mejor funcionalidad del sistema",
        "client" => "Cliente",
        "clients" => "Clientes",
        "company_information" => "Información de la Empresa",
        "financial_information" => "Información Financiera",
        "personal_information" => "Información Personal",
        "passport_information" => "Información del Pasaporte",
        "online_presence" => "Presencia en Línea",
        "additional_settings" => "Configuraciones Adicionales",
        "land-crossing" => "Cruce Terrestre",
        "land-crossings" => "Cruces Terrestres",
        "landcrossing" => "Cruce Terrestre",
        "landcrossings" => "Cruces Terrestres",
        "sea-port" => "Puerto Marítimo",
        "sea-ports" => "Puertos Marítimos",
        "seaport" => "Puerto Marítimo",
        "seaports" => "Puertos Marítimos",
        "air-port" => "Aeropuerto",
        "air-ports" => "Aeropuertos",
        "airport" => "Aeropuerto",
        "airports" => "Aeropuertos",
        "crossing_port" => "Cruce/Puerto",
        "crossings_ports" => "Cruces/Puertos",
        "crossing-port" => "Cruce/Puerto",
        "crossings-ports" => "Cruces/Puertos",
        "land_crossing" => "Cruce Terrestre",
        "international_airport" => "Aeropuerto Internacional",
        "domestic_airport" => "Aeropuerto Nacional",
        "river_port" => "Puerto Fluvial",
        "border_crossing" => "Cruce Fronterizo",
        "operations" => "Operaciones",
        "operational" => "Operativo",
        "24_hours" => "24 Horas",
        "passengers_per_hour" => "Pasajeros por hora",
        "runway_info" => "Información de la Pista",
        "customs_office" => "Oficina de Aduanas",
        "immigration_office" => "Oficina de Inmigración",
        "under_construction" => "En Construcción",
        "operating_information" => "Información Operativa",
        "customs" => "Aduanas",
        "immigration" => "Inmigración",
        "duty_free" => "Libre de Impuestos",
        "vip_lounge" => "Sala VIP",
        "currency_exchange" => "Cambio de Divisas",
        "shops" => "Tiendas",
        "cargo_handling" => "Manejo de Carga",
        "passenger_terminal" => "Terminal de Pasajeros",
        "air_transport" => "Transporte Aéreo",
        "air_transports" => "Transportes Aéreos",
        "air-transport" => "Transporte Aéreo",
        "air-transports" => "Transportes Aéreos",
        "airport_name" => "Nombre del Aeropuerto",
        "airport_name_ar" => "Nombre del Aeropuerto (Árabe)",
        "airport_information" => "Información del Aeropuerto",
        "regional" => "Regional",
        "military" => "Militar",
        "charter_company" => "Compañía Chárter",
        "charter_companies" => "Compañías Chárter",
        "cargo_airline" => "Aerolínea de Carga",
        "cargo_airlines" => "Aerolíneas de Carga",
        "aircraft_operator" => "Operador de Aeronaves",
        "aircraft_operators" => "Operadores de Aeronaves",
        "aircraft_manufacturer" => "Fabricante de Aeronaves",
        "aircraft_manufacturers" => "Fabricantes de Aeronaves",
        "scheduled" => "Programado",
        "charter" => "Chárter",
        "cargo" => "Carga",
        "private" => "Privado",
        "mixed" => "Mixto",
        "is_international" => "Servicio Internacional",
        "is_domestic" => "Servicio Nacional",
        "booking_phone" => "Teléfono de Reservas",
        "customer_service_phone" => "Teléfono de Atención al Cliente",
        "license_number" => "Número de Licencia",
        "tax_number" => "Número de Impuestos",
        "certifications" => "Certificaciones",
        "destinations" => "Destinos",
        "cabin_classes" => "Clases de Cabina",
        "has_frequent_flyer" => "Tiene Programa de Viajero Frecuente",
        "annual_revenue" => "Ingresos Anuales",
        "annual_passengers" => "Pasajeros Anuales",
        "safety_rating_agency" => "Agencia de Calificación de Seguridad",
        "accident_count" => "Conteo de Accidentes",
        "last_safety_audit" => "Última Auditoría de Seguridad",
        "partnerships" => "Asociaciones",
        "codeshare_agreements" => "Acuerdos de Código Compartido",
        "suspended" => "Suspendido",
        "merged" => "Fusionado",
        "bankrupt" => "En Bancarrota",
        "not_specified" => "No Especificado",
        "star_alliance" => "Star Alliance",
        "oneworld" => "OneWorld",
        "skyteam" => "SkyTeam",
        "economy" => "Económica",
        "premium_economy" => "Económica Premium",
        "business" => "Ejecutiva",
        "first_class" => "Primera Clase",
        "baggage_handling" => "Manejo de Equipaje",
        "ground_services" => "Servicios Terrestres",
        "fueling" => "Abastecimiento de Combustible",
        "cargo_services" => "Servicios de Carga",
        "passenger_services" => "Servicios a Pasajeros",
        "ship_services" => "Servicios Marítimos",
        "inspection_services" => "Servicios de Inspección",
        "document_processing" => "Procesamiento de Documentos",
        "unesco_site" => "Patrimonio de la Humanidad UNESCO",
        "sites_theme" => "Tema de Sitios",
        "site" => "Sitio",
        "sites" => "Sitios",
        "tourist-site" => "Sitio Turístico",
        "tourist-sites" => "Sitios Turísticos",
        "tourist_sites" => "Sitios Turísticos",
        "tourist-service" => "Servicio Turístico",
        "tourist-services" => "Servicios Turísticos",
        "tourist_services" => "Servicios Turísticos",
        "service_information" => "Información del Servicio",
        "basic_information" => "Información Básica",
        "geographical_details" => "Detalles Geográficos",
        "entry_information" => "Información de Entrada",
        "service_contact_information" => "Información de Contacto",
        "facilities_services" => "Instalaciones y Servicios",
        "service_facilities_services" => "Instalaciones y Servicios",
        "service_media_resources" => "Medios y Recursos",
        "service_visitor_information" => "Información para Visitantes",
        "service_administrative_info" => "Información Administrativa",
        "service_entry_fees" => "Tarifas de Entrada",
        "service_main_image" => "Imagen Principal",
        "service_gallery_images" => "Imágenes de la Galería",
        "service_virtual_tour_url" => "URL del Recorrido Virtual",
        "service_video_url" => "URL del Video",
        "service_estimated_visit_duration" => "Duración Estimada de la Visita",
        "service_difficulty_level" => "Nivel de Dificultad",
        "service_is_featured" => "Destacado",
        "service_is_verified" => "Verificado",
        "service_is_free_entry" => "Entrada Gratuita",
        "service_is_24_7" => "24 Horas",
        "service_has_parking" => "Tiene Estacionamiento",
        "service_has_restaurant" => "Tiene Restaurante",
        "service_has_gift_shop" => "Tiene Tienda de Regalos",
        "service_has_restrooms" => "Tiene Baños",
        "service_wheelchair_accessible" => "Accesible en Silla de Ruedas",
        "service_facilities" => "Instalaciones",
        "tags" => "Etiquetas",
        "birth_date" => "Fecha de Nacimiento",
        "age" => "Edad (Años)",
        "home_city" => "Ciudad de Origen",
        "operating_days" => "Días de Operación",
        "best_visit_time" => "Mejor Época de Visita",
        "age_restrictions" => "Restricciones de Edad",
        "special_hours" => "Horarios Especiales",
        "total_reviews" => "Total de Reseñas",
        "popularity_score" => "Puntuación de Popularidad",
        "opening_time" => "Hora de Apertura",
        "closing_time" => "Hora de Cierre",
        "pricing_model" => "Modelo de Precios",
        "pricing_unit_value" => "Valor Unitario de Precio",
        "cost_adult" => "Costo Adulto",
        "cost_child" => "Costo Niño",
        "price_child" => "Precio Niño",
        "service_seasons" => "Temporadas del Servicio",
        "seasonal_prices" => "Precios de Temporada",
        "child_min_age" => "Edad Mínima del Niño",
        "child_max_age" => "Edad Máxima del Niño",
        "price_foreigner_adult" => "Precio Adulto Extranjero",
        "price_foreigner_child" => "Precio Niño Extranjero",
        "price_arab_adult" => "Precio Adulto Árabe",
        "price_arab_child" => "Precio Niño Árabe",
        "price_local_adult" => "Precio Adulto Local",
        "price_local_child" => "Precio Niño Local",
        "price_resident_adult" => "Precio Adulto Residente",
        "price_resident_child" => "Precio Niño Residente",
        "target_modules" => "Módulos de Destino",
        "is_tax_inclusive" => "Incluye Impuestos",
        "tax_configuration" => "Configuración de Impuestos",
        "min_participants" => "Mínimo de Participantes",
        "max_participants" => "Máximo de Participantes",
        "booking_required" => "Requiere Reserva",
        "cancellation_policy" => "Política de Cancelación",
        "is_free" => "Es Gratis",
        "is_refundable" => "Es Reembolsable",
        "duration_minutes" => "Duración (Minutos)",
        "basic_info_settings" => "Información Básica y Configuraciones",
        "service_name" => "Nombre del Servicio",
        "service_name_ar" => "Nombre del Servicio (Árabe)",
        "supplier_name" => "Nombre del Proveedor",
        "sort_order" => "Orden de Clasificación",
        "service_code" => "Código del Servicio",
        "address" => "Dirección",
        "pricing_configuration" => "Configuración de Precios",
        "per_unit" => "Por Unidad",
        "per_person_per_day" => "Por Persona Por Día",
        "per_group_per_day" => "Por Grupo Por Día",
        "per_trip" => "Por Viaje",
        "per_tour" => "Por Tour",
        "per_car" => "Por Automóvil",
        "detailed_pricing" => "Precios Detallados",
        "is_24_7" => "Operación 24/7",
        "difficulty_level" => "Nivel de Dificultad",
        "easy" => "Fácil",
        "medium" => "Medio",
        "hard" => "Difícil",
        "contact" => "Contacto",
        "policies" => "Políticas",
        "media" => "Medios",
        "tours" => "Tours",
        "hotels" => "Hoteles",
        "transport" => "Transporte",
        "restaurants" => "Restaurantes",
        "transportationCompanies" => "Compañías de Transporte",
        "transportation_companies" => "Compañías de Transporte",
        "qty" => "Cantidad",
        "value" => "Valor",
        "percentage" => "Porcentaje",
        "fixed_amount" => "Monto Fijo",
        "foreigner" => "Extranjero",
        "arab" => "Árabe",
        "resident" => "Residente",
        "pricing_engine" => "Motor de Precios",
        "pricing_engine_desc" => "Configure su estructura de precios con soporte para tarifas planas y variaciones estacionales",
        "taxes_fees" => "Impuestos y Tarifas",
        "taxes" => "Impuestos",
        "commissions" => "Comisiones",
        "flat_rate" => "Modo de Tarifa Plana",
        "flat_rate_desc" => "Establezca un precio único aplicable a todos los clientes",
        "seasonal_pricing_desc" => "Establezca precios específicos para temporadas como vacaciones o verano. El sistema utilizará estos precios durante el rango de fechas.",
        "valid_from" => "Válido Desde",
        "valid_until" => "Válido Hasta",
        "pricing_information" => "Información de Precios",
        "target_modules_context" => "Seleccione a qué módulos se aplica este servicio",
        "validity_period_optional" => "Período de Validez (Opcional)",
        "add_season_group" => "Agregar Grupo de Temporada",
        "yes_inclusive" => "Sí, Incluido",
        "no_exclusive" => "No, Excluido",
        "applicable_taxes" => "Impuestos Aplicables",
        "add_tax" => "Agregar Impuesto",
        "taxes_desc" => "Definir impuestos que se aplican a este servicio",
        "media_description" => "Sube fotos, videos e imágenes de galería para este servicio",
        "images_gallery" => "Imágenes de la Galería",
        "season_name_desc" => "Ingrese un nombre descriptivo para esta temporada (ej. Temporada de Verano)",
        "date_ranges" => "Rangos de Fechas",
        "applies_to" => "Se Aplica A",
        "all_nationalities" => "Todas las Nacionalidades",
        "select_one_or_more" => "Seleccione uno o más",
        "seasonal_pricing" => "Precios Estacionales",
        "adult_age_range" => "Rango de Edad de Adultos",
        "infant_age_range" => "Rango de Edad de Bebés",
        "min_age" => "Edad Mínima",
        "max_age" => "Edad Máxima",
        "infant_min_age" => "Edad Mínima Bebé",
        "infant_max_age" => "Edad Máxima Bebé",
        "comm" => "Comisión",
        "commission" => "Comisión",
        "local_citizen" => "Ciudadano Local",
        "local_citizens" => "Ciudadanos Locales",
        "adult" => "Adulto",
        "child" => "Niño",
        "child_young" => "Niño Pequeño",
        "child_older" => "Niño Mayor",
        "infant" => "Bebé",
        "cost" => "Costo",
        "pricing_details" => "Detalles de Precios",
        "choose_from_media" => "Elegir de Medios",
        "primary" => "Principal",
        "add_custom_nationality" => "Agregar Nacionalidad Personalizada",
        "add_subregion_pricing" => "Agregar Precios por Subregión",
        "custom_nationalities" => "Nacionalidades Personalizadas",
        "subregion_pricing" => "Precios por Subregión",
        "enter_prices_for_the_selected_subregions" => "Ingrese los precios para las subregiones seleccionadas",
        "price_includes_tax" => "El Precio Incluye Impuestos",
        "historical" => "Histórico",
        "natural" => "Natural",
        "cultural" => "Cultural",
        "religious" => "Religioso",
        "recreational" => "Recreativo",
        "archaeological" => "Arqueológico",
        "museum" => "Museo",
        "park" => "Parque",
        "beach" => "Playa",
        "mountain" => "Montaña",
        "monument" => "Monumento",
        "ticket" => "Entrada",
        "foreigners" => "Extranjeros",
        "local" => "Local",
        "residents" => "Residentes",
        "additional_pricing" => "Precios Adicionales",
        "additional_options" => "Opciones Adicionales",
        "local_guide_price" => "Precio Guía Local",
        "club_car_price" => "Precio Coche de Club",
        "has_unified_ticket" => "Tiene Entrada Unificada",
        "visitor_information" => "Información de Visitantes",
        "average_rating" => "Calificación Promedio",
        "child_policy" => "Política de Niños",
        "service_details" => "Detalles del Servicio",
        "ratings_reviews" => "Calificaciones y Reseñas",
        "location_details" => "Detalles de Ubicación",
        "map_preview" => "Vista Previa del Mapa",
        "per_child_foreigners" => "Por Niño (Extranjeros)",
        "per_child_local" => "Por Niño (Local)",
        "per_child_arab" => "Por Niño (Árabe)",
        "per_adult_residents" => "Por Adulto (Residentes)",
        "per_child_residents" => "Por Niño (Residentes)",
        "pricing_residents" => "Precios para Residentes",
        "pricing_arab" => "Precios para Árabes",
        "pricing_foreigners" => "Precios para Extranjeros",
        "pricing_local" => "Precios Locales",
        "non_accommodated_visitors" => "Visitantes No Alojados",
        "non_accommodated_visitors_adult" => "Visitantes No Alojados (Adulto)",
        "non_accommodated_visitors_child" => "Visitantes No Alojados (Niño)",
        "annual_holidays" => "Días Festivos Anuales",
        "operating_schedule" => "Horario de Operación",
        "special_schedules" => "Horarios Especiales",
        "day_off" => "Día Libre",
        "yearly_holidays" => "Vacaciones Anuales"
    ]
];

function updateNestedArray(&$original, $newValues) {
    foreach ($newValues as $key => $value) {
        if (is_array($value) && isset($original[$key]) && is_array($original[$key])) {
            updateNestedArray($original[$key], $value);
        } else {
            $original[$key] = $value;
        }
    }
}

function exportArrayToPhpSafeHelper($array, $indent = 1) {
    $spaces = str_repeat("    ", $indent);
    $content = "[\n";
    foreach ($array as $key => $value) {
        $safeKey = addcslashes((string)$key, "'\\");
        if (is_array($value)) {
            $content .= $spaces . "'$safeKey' => " . exportArrayToPhpSafeHelper($value, $indent + 1) . ",\n";
        } else {
            $safeValue = addcslashes((string)$value, "'\\");
            $content .= $spaces . "'$safeKey' => '$safeValue',\n";
        }
    }
    $content .= str_repeat("    ", $indent - 1) . "]";
    return $content;
}

function exportArrayToPhpSafe($array) {
    return "<?php\n\nreturn " . exportArrayToPhpSafeHelper($array) . ";\n";
}

$count = 0;

foreach ($es_translations as $filename => $translations) {
    $filePath = $basePath . '/' . $filename;
    
    if (file_exists($filePath)) {
        $existingData = include $filePath;
        if (!is_array($existingData)) {
            $existingData = [];
        }
    } else {
        $existingData = [];
    }
    
    updateNestedArray($existingData, $translations);
    $count += count($translations);
    
    $newContent = exportArrayToPhpSafe($existingData);
    file_put_contents($filePath, $newContent);
    echo "-> $filename: Updated with 300 translated Spanish values.\n";
}

echo "=====================================\n";
echo "SUCCESS! Applied Part 2 ($count keys) for Spanish.\n";
echo "=====================================\n";

?>
