<?php
$basePath = __DIR__ . '/resources/lang/es';
$filePath = $basePath . '/main.php';
$data = include $filePath;

$nested = [
    'main' => [
        'internal_title' => 'Título Interno',
        'active_status' => 'Estado Activo',
        'save_changes' => 'Guardar Cambios',
        'saving' => 'Guardando...',
        'manage_system_columns' => 'Gestionar Columnas del Sistema',
        'dashboard_subtitle' => 'Subtítulo del Panel',
        'please_wait' => 'Por favor espere...',
        'available_columns' => 'Columnas Disponibles',
        'selected' => 'Seleccionado',
        'no_columns_found_title' => 'No se encontraron columnas',
        'no_columns_found_desc' => 'No hay columnas disponibles para este módulo.',
        'import_history' => 'Historial de Importación',
        'processing' => 'Procesando',
        'clear_history' => 'Borrar Historial',
        'importing_data' => 'Importando datos',
        'ready_to_start_import' => 'Listo para iniciar importación',
        'please_wait_importing' => 'Por favor espere, importando...',
        'start' => 'Iniciar',
        'records_processed' => 'Registros procesados',
        'estimated_time' => 'Tiempo estimado',
        'import_started' => 'Importación iniciada',
        'found_records' => 'Registros encontrados',
        'fetching_operations' => 'Obteniendo operaciones',
        'processing_next_batch' => 'Procesando siguiente lote',
        'cancel_import' => 'Cancelar Importación',
        'queued_waiting' => 'En cola de espera',
        'cancel_queued' => 'Cancelar de la cola',
        'do_not_refresh_warning' => '¡No actualice la página durante la importación!',
        'date' => 'Fecha',
        'user' => 'Usuario',
        'source' => 'Fuente',
        'details' => 'Detalles',
        'file_upload' => 'Subir Archivo',
        'completed' => 'Completado',
        'failed' => 'Fallido',
        'queued' => 'En Cola',
        'no_history_records' => 'No hay registros de historial.',
        'media-files' => 'Archivos Multimedia',
        'media-file' => 'Archivo Multimedia',
        'all_types' => 'Todos los Tipos',
        'images' => 'Imágenes',
        'videos' => 'Videos',
        'documents' => 'Documentos',
        'spreadsheets' => 'Hojas de Cálculo',
        'other' => 'Otro',
        'all_collections' => 'Todas las Colecciones',
        'all_status' => 'Todos los Estados',
        'grid_length' => 'Tamaño de Cuadrícula',
        'no_files_found' => 'No se encontraron archivos.',
        'meals' => 'Comidas',
        'meal' => 'Comida',
        'name_ar' => 'Nombre (Árabe)',
        'meal_type' => 'Tipo de Comida',
        'breakfast' => 'Desayuno',
        'lunch' => 'Almuerzo',
        'dinner' => 'Cena',
        'season' => 'Temporada',
        'fixed_price_all_year' => 'Precio Fijo Todo el Año',
        'currency' => 'Moneda',
        'fit_pricing' => 'Precio FIT',
        'price_adult' => 'Precio Adulto',
        'price_child_6_11' => 'Precio Niño 6-11',
        'price_child_under_6' => 'Precio Niño Menor de 6',
        'group_pricing' => 'Precio de Grupo',
        'min_group_size' => 'Tamaño Mínimo de Grupo',
        'description' => 'Descripción',
        'notes' => 'Notas',
        'is_included' => 'Incluido',
        'is_supplement' => 'Es Suplemento',
        'is_active' => 'Activo',
        'pricings' => 'Precios',
        'pricing' => 'Precio',
        'vehicle_type' => 'Tipo de Vehículo',
        'price' => 'Precio',
        'tax' => 'Impuesto',
        'rooms' => 'Habitaciones',
        'room' => 'Habitación',
        'max_occupancy' => 'Ocupación Máxima',
        'occupancy_details' => 'Detalles de Ocupación',
        'price_per_person_double' => 'Precio por Persona (Doble)',
        'single_room_supplement' => 'Suplemento Habitación Individual',
        'triple_room_discount' => 'Descuento Habitación Triple',
        'third_person_price' => 'Precio Tercera Persona',
        'extra_bed_price' => 'Precio Cama Extra',
        'sea_view_supplement' => 'Suplemento Vista al Mar',
        'season_from' => 'Temporada Desde',
        'season_to' => 'Temporada Hasta',
        'supplements' => 'Suplementos',
        'supplement' => 'Suplemento',
        'price_type' => 'Tipo de Precio',
        'per_person' => 'Por Persona',
        'per_room' => 'Por Habitación',
        'per_night' => 'Por Noche',
        'one_time' => 'Una Vez',
        'is_mandatory' => 'Es Obligatorio',
        'vehicle_types' => 'Tipos de Vehículo',
        'company' => 'Compañía',
        'min_capacity' => 'Capacidad Mínima',
        'max_capacity' => 'Capacidad Máxima',
        'has_luggage' => 'Tiene Equipaje',
        'is_air_conditioning' => 'Aire Acondicionado',
        'notifications' => 'Notificaciones',
        'mark_all_read' => 'Marcar Todo como Leído',
        'mark_read' => 'Marcar como Leído',
        'mark_unread' => 'Marcar como No Leído',
        'no_notifications' => 'Sin Notificaciones',
        'view_all_notifications' => 'Ver Todas las Notificaciones',
        'notification' => 'Notificación',
        'notification_type' => 'Tipo de Notificación',
        'system' => 'Sistema',
        'push' => 'Push',
        'custom' => 'Personalizado',
        'type' => 'Tipo',
        'booking' => 'Reserva',
        'payment' => 'Pago',
        'trip' => 'Viaje',
        'theme_customizer' => 'Personalizador de Tema',
        'manage_theme_colors' => 'Gestionar Colores del Tema',
        'back' => 'Volver',
        'reset_defaults' => 'Restablecer Predeterminados',
        'loading' => 'Cargando...',
        'brand_colors' => 'Colores de Marca',
        'primary_color' => 'Color Primario',
        'secondary_color' => 'Color Secundario',
        'dark_color' => 'Color Oscuro',
        'state_colors' => 'Colores de Estado',
        'success_color' => 'Color de Éxito',
        'info_color' => 'Color de Información',
        'warning_color' => 'Color de Advertencia',
        'danger_color' => 'Color de Peligro',
        'sidebar_colors' => 'Colores de la Barra Lateral',
        'sidebar_bg_color' => 'Color de Fondo de la Barra Lateral',
        'sidebar_text_color' => 'Color del Texto de la Barra Lateral',
        'sidebar_active_color' => 'Color Activo de la Barra Lateral',
        'ui_elements_preview' => 'Vista Previa de Elementos UI',
        'types' => 'Tipos',
        'countries' => 'Países',
        'elevation' => 'Elevación',
        'marketing_name' => 'Nombre Comercial',
        'official_full_name' => 'Nombre Oficial Completo',
        'alliance' => 'Alianza',
        'frequent_flyer_program_name' => 'Nombre del Programa de Viajero Frecuente',
        'airline_type' => 'Tipo de Aerolínea',
        'airline_type_code' => 'Código de Tipo de Aerolínea',
        'airline_home_country' => 'País de Origen de la Aerolínea',
        'airline_home_country_alpha_2_code' => 'Código Alfa-2 del País',
        'airline_home_country_alpha_3_code' => 'Código Alfa-3 del País',
        'airline_home_city_iata_code' => 'Código IATA de Ciudad de Origen',
        'year_of_foundation' => 'Año de Fundación',
        'official_website' => 'Sitio Web Oficial',
        'baggage_policy_url' => 'URL de Política de Equipaje',
        'web_check_in_url' => 'URL de Check-in Web',
        'contact_information' => 'Información de Contacto',
        'local_phone_number' => 'Número de Teléfono Local',
        'international_phone_number' => 'Número de Teléfono Internacional',
        'website' => 'Sitio Web',
        'is_lowcost' => 'Es Bajo Costo',
        'regions' => 'Regiones',
        'subregions' => 'Subregiones',
        'fields' => 'Campos',
        'code' => 'Código',
        'service_type' => 'Tipo de Servicio',
        'established_date' => 'Fecha de Fundación',
        'hub_airport' => 'Aeropuerto Hub',
        'fleet_information' => 'Información de Flota',
        'fleet_size' => 'Tamaño de Flota',
        'aircraft' => 'Aeronave',
        'passenger_capacity' => 'Capacidad de Pasajeros',
        'passengers' => 'Pasajeros',
        'cargo_capacity' => 'Capacidad de Carga',
        'tons' => 'Toneladas',
        'aircraft_types' => 'Tipos de Aeronave',
        'map' => 'Mapa',
        'coordinates' => 'Coordenadas',
        'view_on_google_maps' => 'Ver en Google Maps',
        'location_information' => 'Información de Ubicación',
        'safety_performance' => 'Rendimiento de Seguridad',
        'safety_rating' => 'Calificación de Seguridad',
        'on_time_performance' => 'Puntualidad',
        'operational_status' => 'Estado Operacional',
        'international' => 'Internacional',
        'domestic' => 'Nacional',
        'frequent_flyer_program' => 'Programa de Viajero Frecuente',
        'facilities' => 'Instalaciones',
        'features' => 'Características',
    ]
];

function updateNestedArray(&$original, $newValues) {
    foreach ($newValues as $key => $value) {
        if (is_array($value) && isset($original[$key]) && is_array($original[$key])) {
            updateNestedArray($original[$key], $value);
        } else {
            $original[$key] = $value;
        }
    }
}
function exportArrayToPhpSafeHelper($array, $indent = 1) {
    $spaces = str_repeat("    ", $indent);
    $content = "[\n";
    foreach ($array as $key => $value) {
        $safeKey = addcslashes((string)$key, "'\\");
        if (is_array($value)) {
            $content .= $spaces . "'$safeKey' => " . exportArrayToPhpSafeHelper($value, $indent + 1) . ",\n";
        } else {
            $safeValue = addcslashes((string)$value, "'\\");
            $content .= $spaces . "'$safeKey' => '$safeValue',\n";
        }
    }
    $content .= str_repeat("    ", $indent - 1) . "]";
    return $content;
}
function exportArrayToPhpSafe($array) {
    return "<?php\n\nreturn " . exportArrayToPhpSafeHelper($array) . ";\n";
}

updateNestedArray($data, $nested);
file_put_contents($filePath, exportArrayToPhpSafe($data));
echo "-> main.php (ES): Part 2 applied.\n";
echo "=====================================\n";
echo "SUCCESS! Applied ES fix part 2.\n";
echo "=====================================\n";
