<?php
$basePath = __DIR__ . '/resources/lang/es';
$filePath = $basePath . '/main.php';
$data = include $filePath;

$nested = [
    'dashboard_tasks' => [
        'showing' => 'Mostrando',
        'to' => 'a',
        'of' => 'de',
        'results' => 'resultados',
        'previous' => 'Anterior',
        'next' => 'Siguiente',
    ],
    'maps' => [
        'continent' => 'continente',
        'continents' => 'continentes',
        'asia' => 'Asia',
        'africa' => 'África',
        'europe' => 'Europa',
        'north america' => 'América del Norte',
        'south america' => 'América del Sur',
        'australia' => 'Australia',
        'antarctica' => 'Antártida',
        'asia/riyadh' => 'Asia/Riad',
        'asia/dubai' => 'Asia/Dubái',
        'asia/kuwait' => 'Asia/Kuwait',
        'asia/baghdad' => 'Asia/Bagdad',
        'africa/cairo' => 'África/El Cairo',
        'europe/london' => 'Europa/Londres',
        'america/new_york' => 'América/Nueva York',
        'riyadh' => 'Riad',
        'dubai' => 'Dubái',
        'kuwait' => 'Kuwait',
        'baghdad' => 'Bagdad',
        'cairo' => 'El Cairo',
        'london' => 'Londres',
        'america' => 'América',
        'new_york' => 'Nueva York',
        'august' => 'Agosto',
        'time' => 'AM',
    ],
    'sidebar' => [
        'Ai-Agent' => 'Agente IA',
        'users management' => 'Gestión de Usuarios',
        'users' => 'Usuarios',
        'automation' => 'Automatización',
        'automation_settings' => 'Configuración de Automatización',
    ],
    'main' => [
        'you_must_add' => 'Debe agregar',
        'and' => 'y',
        'first' => 'primero',
        'import_file' => 'Importar Archivo',
        'upload_and_import' => 'Subir e Importar',
        'cancel' => 'Cancelar',
        'export' => 'Exportar',
        'list' => 'Lista',
        'grid' => 'Cuadrícula',
        'yes' => 'Sí',
        'no' => 'No',
        'delete' => 'Eliminar',
        'items' => 'elementos',
        'pdf' => 'PDF',
        'csv' => 'CSV',
        'xlsx' => 'XLSX',
        'export_template' => 'Exportar Plantilla',
        'columns' => 'Columnas',
        'custom_fields' => 'Campos Personalizados',
        'select' => 'Seleccionar',
        'current' => 'Actual',
        'hidden_field' => 'Campo Oculto',
        'sort_by' => 'Ordenar Por',
        'filter_by' => 'Filtrar Por',
        'search_in' => 'Buscar En',
        'type_to_search' => 'Escriba para buscar...',
        'actions' => 'Acciones',
        'view_action' => 'Ver',
        'create' => 'Crear',
        '$model' => '$model',
        'edit' => 'Editar',
        'force_delete' => 'Eliminar Definitivamente',
        'reset_filters' => 'Restablecer Filtros',
        'save_and_add_another' => 'Guardar y Agregar Otro',
        'show' => 'Mostrar',
        'countries_' => 'Países',
        'currencies_' => 'Monedas',
        'regions_' => 'Regiones',
        'last_import' => 'Última Importación',
        'records' => 'Registros',
        'requirements_not_met' => 'Requisitos No Cumplidos',
        'import_from_url' => 'Importar desde URL',
        'import_url' => 'URL de Importación',
        'make_sure_url_is_public' => 'Asegúrese de que la URL sea pública',
        'save_link_only' => 'Guardar Solo el Enlace',
        'update_from_url' => 'Actualizar desde URL',
        'manual_file_upload' => 'Subida Manual de Archivo',
        'import_type' => 'Tipo de Importación',
        'please_select_option' => 'Por favor seleccione una opción',
        'preview' => 'Vista Previa',
        'error' => 'Error',
        'please_enter_valid_url' => 'Ingrese una URL válida',
        'drive_save_confirm_title' => 'Confirmar Guardado desde Drive',
        'drive_save_confirm_message' => '¿Desea guardar este enlace de Google Drive?',
        'save' => 'Guardar',
        'drive_update_confirm_title' => 'Confirmar Actualización desde Drive',
        'drive_update_confirm_line1' => 'Se descargará el archivo desde Google Drive.',
        'drive_update_confirm_line2' => 'Se reemplazarán los datos existentes.',
        'drive_update_confirm_line3' => 'Esta acción no se puede deshacer.',
        'drive_update_confirm_line4' => '¿Desea continuar?',
        'yes_update_it' => 'Sí, Actualizar',
        'fetching' => 'Obteniendo...',
        'clear_history_confirm_title' => 'Confirmar Borrado de Historial',
        'clear_history_confirm_message' => '¿Está seguro de que desea borrar todo el historial de importación?',
        'yes_clear' => 'Sí, Borrar',
        'latitude' => 'Latitud',
        'longitude' => 'Longitud',
        'location' => 'Ubicación',
        'no_data' => 'Sin Datos',
        'metadata' => 'Metadatos',
        'created_by' => 'Creado Por',
        'na' => 'N/D',
        'created_at' => 'Creado El',
        'updated_by' => 'Actualizado Por',
        'updated_at' => 'Actualizado El',
        'region' => 'Región',
        'add' => 'Agregar',
        'subregion' => 'Subregión',
        'country' => 'País',
        'states' => 'Estados',
        'state' => 'Estado',
        'cities' => 'Ciudades',
        'city' => 'Ciudad',
        'dark_mode' => 'Modo Oscuro',
        'light_mode' => 'Modo Claro',
        'search' => 'Buscar',
        'gallery' => 'Galería',
        'total_images' => 'Total de Imágenes',
        'null' => 'Nulo',
        'modules' => 'Módulos',
        'none' => 'Ninguno',
        'quick_edit' => 'Edición Rápida',
        'view_on_map' => 'Ver en el Mapa',
        'years' => 'Años',
        'individual' => 'Individual',
        'corporate' => 'Corporativo',
        'h' => 'h',
        'km' => 'km',
        'pax' => 'pax',
        'unknown' => 'Desconocido',
        'read' => 'Leído',
        'unread' => 'No Leído',
        'readed' => 'Leído',
        'unreaded' => 'No Leído',
        'active' => 'Activo',
        'inactive' => 'Inactivo',
        'blacklisted' => 'En Lista Negra',
        'male' => 'Masculino',
        'female' => 'Femenino',
        'pricing_unit' => 'Unidad de Precio',
        'pricing_type' => 'Tipo de Precio',
        'site_type' => 'Tipo de Sitio',
        'site_category' => 'Categoría del Sitio',
        'site_theme' => 'Tema del Sitio',
        'supplier_type' => 'Tipo de Proveedor',
        'users' => 'Usuarios',
        'name' => 'Nombre',
        'email' => 'Correo Electrónico',
        'total' => 'Total',
        'showing' => 'Mostrando',
        'of' => 'de',
        'page' => 'Página',
        'delete_selected' => 'Eliminar Seleccionados',
        'reset_sort' => 'Restablecer Orden',
        'clear_search' => 'Borrar Búsqueda',
        'type_1_filters' => 'Filtros Tipo 1',
        'type_2_filters' => 'Filtros Tipo 2',
        'all' => 'Todos',
        'manage_columns' => 'Gestionar Columnas',
        'save_as_system_default' => 'Guardar como Predeterminado del Sistema',
        'all_columns' => 'Todas las Columnas',
        'clear_all' => 'Borrar Todo',
        'reset_to_default_desc' => 'Restablecer las columnas a la configuración predeterminada del sistema',
        'reset_to_default' => 'Restablecer Predeterminado',
        'close' => 'Cerrar',
        'apply' => 'Aplicar',
        'progress' => 'Progreso',
        'items_per_page' => 'Elementos por Página',
        'previous' => 'Anterior',
        'next' => 'Siguiente',
        'showing_count' => 'Mostrando',
        'of_total' => 'del total',
        'search_placeholder' => 'Buscar...',
        'import_csv' => 'Importar CSV',
        'room_rates' => 'Tarifas de Habitación',
        'meal_rates' => 'Tarifas de Comida',
        'room_rate' => 'Tarifa de Habitación',
        'meal_rate' => 'Tarifa de Comida',
        'accommodation' => 'Alojamiento',
        'seasons' => 'Temporadas',
        'airlines' => 'Aerolíneas',
        'airline' => 'Aerolínea',
        'page_banners' => 'Banners de Página',
        'add_banner' => 'Agregar Banner',
        'target' => 'Destino',
        'title' => 'Título',
        'status' => 'Estado',
        'no_preview' => 'Sin Vista Previa',
        'are_you_sure' => '¿Está seguro?',
        'no_data_found' => 'No se encontraron datos',
        'edit_banner' => 'Editar Banner',
        'banner_target' => 'Destino del Banner',
        'entire_module' => 'Módulo Completo',
        'specific_route' => 'Ruta Específica',
        'select_module' => 'Seleccionar Módulo',
        'route' => 'Ruta',
        'select_route' => 'Seleccionar Ruta...',
        'banner_design' => 'Diseño del Banner',
        'upload_image' => 'Subir Imagen',
        'color_and_text' => 'Color y Texto',
        'image_tips_title' => 'Consejos para Imágenes',
        'image_tips_format' => 'Formatos: JPG, PNG, WebP',
        'image_tips_dimensions' => 'Dimensiones recomendadas: 1920x400px',
        'image_tips_system' => 'El sistema redimensionará automáticamente',
        'select_banner_image' => 'Seleccionar Imagen del Banner',
        'uploading' => 'Subiendo...',
        'new_preview' => 'Nueva Vista Previa',
        'current_image' => 'Imagen Actual',
        'background_color' => 'Color de Fondo',
        'text_color' => 'Color del Texto',
        'banner_text' => 'Texto del Banner',
        'font_family' => 'Familia de Fuente',
        'font_size' => 'Tamaño de Fuente',
        'live_preview' => 'Vista Previa en Vivo',
        'your_text_here' => 'Su texto aquí',
    ]
];

function updateNestedArray(&$original, $newValues) {
    foreach ($newValues as $key => $value) {
        if (is_array($value) && isset($original[$key]) && is_array($original[$key])) {
            updateNestedArray($original[$key], $value);
        } else {
            $original[$key] = $value;
        }
    }
}
function exportArrayToPhpSafeHelper($array, $indent = 1) {
    $spaces = str_repeat("    ", $indent);
    $content = "[\n";
    foreach ($array as $key => $value) {
        $safeKey = addcslashes((string)$key, "'\\");
        if (is_array($value)) {
            $content .= $spaces . "'$safeKey' => " . exportArrayToPhpSafeHelper($value, $indent + 1) . ",\n";
        } else {
            $safeValue = addcslashes((string)$value, "'\\");
            $content .= $spaces . "'$safeKey' => '$safeValue',\n";
        }
    }
    $content .= str_repeat("    ", $indent - 1) . "]";
    return $content;
}
function exportArrayToPhpSafe($array) {
    return "<?php\n\nreturn " . exportArrayToPhpSafeHelper($array) . ";\n";
}

updateNestedArray($data, $nested);
file_put_contents($filePath, exportArrayToPhpSafe($data));
echo "-> main.php (ES): Part 1 applied.\n";
echo "=====================================\n";
echo "SUCCESS! Applied ES fix part 1.\n";
echo "=====================================\n";
