#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
✅ نظام الترجمة اليدوية الاحترافية الشامل
Professional Manual Comprehensive Translation System
"""

import re
from pathlib import Path
import json

PROJECT_ROOT = Path("g:/MixJo Top downlode mains by dats/for edit/tourism-management-system  13 FEB 2026 0221AM/tourism-management-system")
LANG_DIR = PROJECT_ROOT / "resources" / "lang"
ENGLISH_DIR = LANG_DIR / "en"
OUTPUT_DIR = Path("G:/Translate mixjo VS Code/Translate VSCODE 2")

REQUIRED_FILES = ['auth.php', 'automation.php', 'activity.php', 'languages.php',
                  'messages.php', 'sidebar.php', 'en.php', 'main.php']

def extract_php_array(php_content):
    """استخراج المفاتيح والقيم من ملف PHP"""
    translations = {}
    try:
        match = re.search(r'return\s*\[\s*(.*?)\s*\];', php_content, re.DOTALL)
        if match:
            array_content = match.group(1)
            pattern = r"['\"]([^'\"]+)['\"]\s*=>\s*['\"]([^'\"]*)['\"]"
            matches = re.findall(pattern, array_content)
            for key, value in matches:
                translations[key] = value
    except:
        pass
    return translations

def translate_manually(en_value, language_code):
    """
    ترجمة يدوية احترافية
    Manual professional translation based on context and meaning
    """
    
    # تحويل النص لحروف صغيرة للمقارنة
    text = en_value.lower().strip()
    
    # قاموس الترجمات اليدوية الشامل
    translations = {
        'fr': {
            # Authentication
            'login': 'Connexion',
            'login successful': 'Connexion réussie',
            'logout': 'Déconnexion',
            'logout successful': 'Déconnexion réussie',
            'failed': 'Les identifiants fournis ne correspondent pas à nos enregistrements.',
            'password': 'Le mot de passe fourni est incorrect.',
            'the provided credentials are incorrect': 'Les identifiants fournis ne correspondent pas à nos enregistrements.',
            'the provided password is incorrect': 'Le mot de passe fourni est incorrect.',
            'too many login attempts': 'Trop de tentatives de connexion.',
            'throttle': 'Trop de tentatives de connexion. Veuillez réessayer dans :seconds secondes.',
            'unauthenticated': 'Non authentifié.',
            
            # Automation
            'automation': 'Automatisation',
            'automation settings': 'Paramètres d\'automatisation',
            'automation settings (n8n)': 'Paramètres d\'automatisation (n8n)',
            'add new webhook': 'Ajouter un nouveau webhook',
            'add new webhook (n8n)': 'Ajouter un nouveau webhook (n8n)',
            'edit webhook': 'Modifier le webhook',
            'friendly name': 'Nom convivial',
            'webhook url': 'URL du webhook',
            'event type': 'Type d\'événement',
            'all events': 'Tous les événements',
            'all events (*)': 'Tous les événements (*)',
            'secret token': 'Jeton secret',
            'secret token (optional)': 'Jeton secret (Optionnel)',
            'cancel': 'Annuler',
            'update bridge': 'Mettre à jour le pont',
            'connect to n8n': 'Connectez-vous à n8n',
            'active automation bridges': 'Ponts d\'automatisation actifs',
            'name': 'Nom',
            'event': 'Événement',
            'status': 'Statut',
            'actions': 'Actions',
            'active': 'Actif',
            'paused': 'En pause',
            'recent synchronizations': 'Synchronisations récentes',
            'time': 'Temps',
            'bridge': 'Pont',
            'response': 'Réponse',
            'webhook saved': 'Webhook enregistré avec succès.',
            'webhook saved successfully': 'Webhook enregistré avec succès.',
            'restaurant created': 'Restaurant créé',
            'restaurant updated': 'Restaurant mis à jour',
            'hotel created': 'Hôtel créé',
            'booking created': 'Réservation créée',
            
            # General common terms
            'success': 'Succès',
            'error': 'Erreur',
            'warning': 'Avertissement',
            'save': 'Enregistrer',
            'delete': 'Supprimer',
            'edit': 'Modifier',
            'create': 'Créer',
            'update': 'Mettre à jour',
            'add': 'Ajouter',
            'close': 'Fermer',
            'submit': 'Soumettre',
            'refresh': 'Actualiser',
            'loading': 'Chargement...',
            'no data': 'Aucune donnée',
            'email': 'Adresse e-mail',
            'phone': 'Téléphone',
            'address': 'Adresse',
            'city': 'Ville',
            'country': 'Pays',
            'language': 'Langue',
            'settings': 'Paramètres',
            'profile': 'Profil',
            'dashboard': 'Tableau de bord',
            'export': 'Exporter',
            'import': 'Importer',
            'search': 'Rechercher',
            'filter': 'Filtrer',
            'sort': 'Trier',
            'back': 'Retour',
            'next': 'Suivant',
            'previous': 'Précédent',
            'download': 'Télécharger',
            'upload': 'Télécharger',
        },
        'de': {
            'login': 'Anmelden',
            'login successful': 'Anmeldung erfolgreich',
            'logout': 'Abmelden',
            'logout successful': 'Abmeldung erfolgreich',
            'failed': 'Diese Anmeldedaten entsprechen nicht unseren Aufzeichnungen.',
            'password': 'Das angegebene Passwort ist falsch.',
            'the provided credentials are incorrect': 'Diese Anmeldedaten entsprechen nicht unseren Aufzeichnungen.',
            'the provided password is incorrect': 'Das angegebene Passwort ist falsch.',
            'too many login attempts': 'Zu viele Anmeldeversuche.',
            'throttle': 'Zu viele Anmeldeversuche. Bitte versuchen Sie es in :seconds Sekunden erneut.',
            'unauthenticated': 'Nicht authentifiziert.',
            'automation': 'Automatisierung',
            'automation settings': 'Automatisierungseinstellungen',
            'automation settings (n8n)': 'Automatisierungseinstellungen (n8n)',
            'add new webhook': 'Neuen Webhook hinzufügen',
            'add new webhook (n8n)': 'Neuen Webhook hinzufügen (n8n)',
            'edit webhook': 'Webhook bearbeiten',
            'friendly name': 'Anzeigename',
            'webhook url': 'Webhook-URL',
            'event type': 'Ereignistyp',
            'all events': 'Alle Ereignisse',
            'all events (*)': 'Alle Ereignisse (*)',
            'secret token': 'Geheimes Token',
            'secret token (optional)': 'Geheimes Token (Optional)',
            'cancel': 'Abbrechen',
            'update bridge': 'Brücke aktualisieren',
            'connect to n8n': 'Mit n8n verbinden',
            'active automation bridges': 'Aktive Automatisierungsbrücken',
            'name': 'Name',
            'event': 'Ereignis',
            'status': 'Status',
            'actions': 'Aktionen',
            'active': 'Aktiv',
            'paused': 'Pausiert',
            'recent synchronizations': 'Aktuelle Synchronisierungen',
            'time': 'Zeit',
            'bridge': 'Brücke',
            'response': 'Antwort',
            'webhook saved': 'Webhook erfolgreich gespeichert.',
            'webhook saved successfully': 'Webhook erfolgreich gespeichert.',
            'restaurant created': 'Restaurant erstellt',
            'restaurant updated': 'Restaurant aktualisiert',
            'hotel created': 'Hotel erstellt',
            'booking created': 'Buchung erstellt',
            'success': 'Erfolg',
            'error': 'Fehler',
            'warning': 'Warnung',
            'save': 'Speichern',
            'delete': 'Löschen',
            'edit': 'Bearbeiten',
            'create': 'Erstellen',
            'update': 'Aktualisieren',
            'add': 'Hinzufügen',
            'close': 'Schließen',
            'submit': 'Absenden',
            'refresh': 'Aktualisieren',
            'loading': 'Wird geladen...',
            'no data': 'Keine Daten',
            'email': 'E-Mail',
            'phone': 'Telefon',
            'address': 'Adresse',
            'city': 'Stadt',
            'country': 'Land',
            'language': 'Sprache',
            'settings': 'Einstellungen',
            'profile': 'Profil',
            'dashboard': 'Dashboard',
            'export': 'Exportieren',
            'import': 'Importieren',
            'search': 'Suchen',
            'filter': 'Filtern',
            'sort': 'Sortieren',
            'back': 'Zurück',
            'next': 'Weiter',
            'previous': 'Vorherige',
            'download': 'Herunterladen',
            'upload': 'Hochladen',
        },
        'it': {
            'login': 'Accesso',
            'login successful': 'Accesso riuscito',
            'logout': 'Disconnessione',
            'logout successful': 'Disconnessione riuscita',
            'failed': 'Queste credenziali non corrispondono ai nostri registri.',
            'password': 'La password fornita non è corretta.',
            'the provided credentials are incorrect': 'Queste credenziali non corrispondono ai nostri registri.',
            'the provided password is incorrect': 'La password fornita non è corretta.',
            'too many login attempts': 'Troppi tentativi di accesso.',
            'throttle': 'Troppi tentativi di accesso. Riprova tra :seconds secondi.',
            'unauthenticated': 'Non autenticato.',
            'automation': 'Automazione',
            'automation settings': 'Impostazioni di automazione',
            'automation settings (n8n)': 'Impostazioni di automazione (n8n)',
            'add new webhook': 'Aggiungi nuovo webhook',
            'add new webhook (n8n)': 'Aggiungi nuovo webhook (n8n)',
            'edit webhook': 'Modifica webhook',
            'friendly name': 'Nome visualizzato',
            'webhook url': 'URL webhook',
            'event type': 'Tipo di evento',
            'all events': 'Tutti gli eventi',
            'all events (*)': 'Tutti gli eventi (*)',
            'secret token': 'Token segreto',
            'secret token (optional)': 'Token segreto (Facoltativo)',
            'cancel': 'Annulla',
            'update bridge': 'Aggiorna bridge',
            'connect to n8n': 'Connettiti a n8n',
            'active automation bridges': 'Bridge di automazione attivi',
            'name': 'Nome',
            'event': 'Evento',
            'status': 'Stato',
            'actions': 'Azioni',
            'active': 'Attivo',
            'paused': 'In pausa',
            'recent synchronizations': 'Sincronizzazioni recenti',
            'time': 'Orario',
            'bridge': 'Bridge',
            'response': 'Risposta',
            'webhook saved': 'Webhook salvato con successo.',
            'webhook saved successfully': 'Webhook salvato con successo.',
            'restaurant created': 'Ristorante creato',
            'restaurant updated': 'Ristorante aggiornato',
            'hotel created': 'Hotel creato',
            'booking created': 'Prenotazione creata',
            'success': 'Successo',
            'error': 'Errore',
            'warning': 'Avviso',
            'save': 'Salva',
            'delete': 'Elimina',
            'edit': 'Modifica',
            'create': 'Crea',
            'update': 'Aggiorna',
            'add': 'Aggiungi',
            'close': 'Chiudi',
            'submit': 'Invia',
            'refresh': 'Aggiorna',
            'loading': 'Caricamento in corso...',
            'no data': 'Nessun dato',
            'email': 'Email',
            'phone': 'Telefono',
            'address': 'Indirizzo',
            'city': 'Città',
            'country': 'Paese',
            'language': 'Lingua',
            'settings': 'Impostazioni',
            'profile': 'Profilo',
            'dashboard': 'Cruscotto',
            'export': 'Esporta',
            'import': 'Importa',
            'search': 'Cerca',
            'filter': 'Filtra',
            'sort': 'Ordina',
            'back': 'Indietro',
            'next': 'Avanti',
            'previous': 'Precedente',
            'download': 'Scarica',
            'upload': 'Carica',
        },
        'ja': {
            'login': 'ログイン',
            'login successful': 'ログインに成功しました',
            'logout': 'ログアウト',
            'logout successful': 'ログアウトに成功しました',
            'failed': 'これらの認証情報は当社の記録と一致しません。',
            'password': '提供されたパスワードは正しくありません。',
            'the provided credentials are incorrect': 'これらの認証情報は当社の記録と一致しません。',
            'the provided password is incorrect': '提供されたパスワードは正しくありません。',
            'too many login attempts': 'ログイン試行が多すぎます。',
            'throttle': 'ログイン試行が多すぎます。:seconds秒後にもう一度お試しください。',
            'unauthenticated': '認証されていません。',
            'automation': 'オートメーション',
            'automation settings': 'オートメーション設定',
            'automation settings (n8n)': 'オートメーション設定 (n8n)',
            'add new webhook': '新しいウェブフックを追加',
            'add new webhook (n8n)': '新しいウェブフックを追加 (n8n)',
            'edit webhook': 'ウェブフックを編集',
            'friendly name': '表示名',
            'webhook url': 'ウェブフック URL',
            'event type': 'イベントタイプ',
            'all events': 'すべてのイベント',
            'all events (*)': 'すべてのイベント (*)',
            'secret token': 'シークレットトークン',
            'secret token (optional)': 'シークレットトークン (オプション)',
            'cancel': 'キャンセル',
            'update bridge': 'ブリッジを更新',
            'connect to n8n': 'n8n に接続',
            'active automation bridges': 'アクティブなオートメーションブリッジ',
            'name': '名前',
            'event': 'イベント',
            'status': 'ステータス',
            'actions': 'アクション',
            'active': 'アクティブ',
            'paused': '一時停止',
            'recent synchronizations': '最近の同期',
            'time': '時間',
            'bridge': 'ブリッジ',
            'response': 'レスポンス',
            'webhook saved': 'ウェブフックが正常に保存されました。',
            'webhook saved successfully': 'ウェブフックが正常に保存されました。',
            'restaurant created': 'レストランが作成されました',
            'restaurant updated': 'レストランが更新されました',
            'hotel created': 'ホテルが作成されました',
            'booking created': '予約が作成されました',
            'success': '成功',
            'error': 'エラー',
            'warning': '警告',
            'save': '保存',
            'delete': '削除',
            'edit': '編集',
            'create': '作成',
            'update': '更新',
            'add': '追加',
            'close': '閉じる',
            'submit': '送信',
            'refresh': '更新',
            'loading': '読み込み中...',
            'no data': 'データなし',
            'email': 'メール',
            'phone': '電話',
            'address': '住所',
            'city': '都市',
            'country': '国',
            'language': '言語',
            'settings': '設定',
            'profile': 'プロフィール',
            'dashboard': 'ダッシュボード',
            'export': 'エクスポート',
            'import': 'インポート',
            'search': '検索',
            'filter': 'フィルター',
            'sort': '並び替え',
            'back': '戻る',
            'next': '次へ',
            'previous': '前へ',
            'download': 'ダウンロード',
            'upload': 'アップロード',
        },
        'ru': {
            'login': 'Вход',
            'login successful': 'Вход выполнен успішно',
            'logout': 'Выход',
            'logout successful': 'Выход выполнен успішно',
            'failed': 'Эти учетные данные не соответствуют нашим записям.',
            'password': 'Введённый пароль неправилен.',
            'the provided credentials are incorrect': 'Эти учетные данные не соответствуют нашим записям.',
            'the provided password is incorrect': 'Введённый пароль неправилен.',
            'too many login attempts': 'Слишком много попыток входа.',
            'throttle': 'Слишком много попыток входа. Пожалуйста, попробуйте снова через :seconds секунд.',
            'unauthenticated': 'Не аутентифицирован.',
            'automation': 'Автоматизация',
            'automation settings': 'Параметры автоматизации',
            'automation settings (n8n)': 'Параметры автоматизации (n8n)',
            'add new webhook': 'Добавить новый webhook',
            'add new webhook (n8n)': 'Добавить новый webhook (n8n)',
            'edit webhook': 'Редактировать webhook',
            'friendly name': 'Понятное имя',
            'webhook url': 'URL webhook',
            'event type': 'Тип события',
            'all events': 'Все события',
            'all events (*)': 'Все события (*)',
            'secret token': 'Секретный токен',
            'secret token (optional)': 'Секретный токен (Опционально)',
            'cancel': 'Отмена',
            'update bridge': 'Обновить мост',
            'connect to n8n': 'Подключиться к n8n',
            'active automation bridges': 'Активные мосты автоматизации',
            'name': 'Имя',
            'event': 'evento',
            'status': 'Статус',
            'actions': 'Действия',
            'active': 'Активно',
            'paused': 'Пауза',
            'recent synchronizations': 'Недавние синхронизации',
            'time': 'Время',
            'bridge': 'Мост',
            'response': 'Ответ',
            'webhook saved': 'Webhook успішно сохранён.',
            'webhook saved successfully': 'Webhook успішно сохранён.',
            'restaurant created': 'Ресторан создан',
            'restaurant updated': 'Ресторан обновлен',
            'hotel created': 'Отель создан',
            'booking created': 'Бронь создана',
            'success': 'Успіх',
            'error': 'Ошибка',
            'warning': 'Предупреждение',
            'save': 'Сохранить',
            'delete': 'Удалить',
            'edit': 'Редактировать',
            'create': 'Создать',
            'update': 'Обновить',
            'add': 'Добавить',
            'close': 'Закрыть',
            'submit': 'Отправить',
            'refresh': 'Обновить',
            'loading': 'Загрузка...',
            'no data': 'Нет данных',
            'email': 'Email',
            'phone': 'Телефон',
            'address': 'Адрес',
            'city': 'Города',
            'country': 'Страна',
            'language': 'Язык',
            'settings': 'Параметры',
            'profile': 'Профиль',
            'dashboard': 'Панель управления',
            'export': 'Экспорт',
            'import': 'Импорт',
            'search': 'Поиск',
            'filter': 'Фильтр',
            'sort': 'Сортировка',
            'back': 'Назад',
            'next': 'Далее',
            'previous': 'Предыдущий',
            'download': 'Скачать',
            'upload': 'Загрузить',
        },
        'tr': {
            'login': 'Giriş Yap',
            'login successful': 'Giriş Başarılı',
            'logout': 'Çıkış Yap',
            'logout successful': 'Çıkış Başarılı',
            'failed': 'Bu kimlik bilgileri kayıtlarımızla eşleşmiyor.',
            'password': 'Sağlanan şifre hatalı.',
            'the provided credentials are incorrect': 'Bu kimlik bilgileri kayıtlarımızla eşleşmiyor.',
            'the provided password is incorrect': 'Sağlanan şifre hatalı.',
            'too many login attempts': 'Çok fazla giriş denemesi.',
            'throttle': 'Çok fazla giriş denemesi. Lütfen :seconds saniye içinde tekrar deneyin.',
            'unauthenticated': 'Kimlik doğrulanmadı.',
            'automation': 'Otomasyon',
            'automation settings': 'Otomasyon Ayarları',
            'automation settings (n8n)': 'Otomasyon Ayarları (n8n)',
            'add new webhook': 'Yeni Webhook Ekle',
            'add new webhook (n8n)': 'Yeni Webhook Ekle (n8n)',
            'edit webhook': 'Webhook\'u Düzenle',
            'friendly name': 'Kolay İsim',
            'webhook url': 'Webhook URL\'si',
            'event type': 'Etkinlik Türü',
            'all events': 'Tüm Etkinlikler',
            'all events (*)': 'Tüm Etkinlikler (*)',
            'secret token': 'Gizli Token',
            'secret token (optional)': 'Gizli Token (İsteğe Bağlı)',
            'cancel': 'İptal',
            'update bridge': 'Köprüyü Güncelle',
            'connect to n8n': 'n8n\'e Bağlan',
            'active automation bridges': 'Aktif Otomasyon Köprüleri',
            'name': 'İsim',
            'event': 'Etkinlik',
            'status': 'Durum',
            'actions': 'İşlemler',
            'active': 'Aktif',
            'paused': 'Duraklatıldı',
            'recent synchronizations': 'Son Senkronizasyonlar',
            'time': 'Zaman',
            'bridge': 'Köprü',
            'response': 'Yanıt',
            'webhook saved': 'Webhook başarıyla kaydedildi.',
            'webhook saved successfully': 'Webhook başarıyla kaydedildi.',
            'restaurant created': 'Restoran Oluşturuldu',
            'restaurant updated': 'Restoran Güncellendi',
            'hotel created': 'Otel Oluşturuldu',
            'booking created': 'Rezervasyon Oluşturuldu',
            'success': 'Başarılı',
            'error': 'Hata',
            'warning': 'Uyarı',
            'save': 'Kaydet',
            'delete': 'Sil',
            'edit': 'Düzenle',
            'create': 'Oluştur',
            'update': 'Güncelle',
            'add': 'Ekle',
            'close': 'Kapat',
            'submit': 'Gönder',
            'refresh': 'Yenile',
            'loading': 'Yükleniyor...',
            'no data': 'Veri Yok',
            'email': 'E-posta',
            'phone': 'Telefon',
            'address': 'Adres',
            'city': 'Şehir',
            'country': 'Ülke',
            'language': 'Dil',
            'settings': 'Ayarlar',
            'profile': 'Profil',
            'dashboard': 'Pano',
            'export': 'Dışa Aktar',
            'import': 'İçe Aktar',
            'search': 'Ara',
            'filter': 'Filtre',
            'sort': 'Sırala',
            'back': 'Geri',
            'next': 'Sonraki',
            'previous': 'Önceki',
            'download': 'İndir',
            'upload': 'Yükle',
        },
        'he': {
            'login': 'כניסה',
            'login successful': 'ההתחברות בוצעה בהצלחה',
            'logout': 'יציאה',
            'logout successful': 'היציאה בוצעה בהצלחה',
            'failed': 'שם ססמה אלה אין התאמה לרשומות שלנו',
            'password': 'הססמה שסופקה אינה נכונה.',
            'the provided credentials are incorrect': 'שם ססמה אלה אין התאמה לרשומות שלנו',
            'the provided password is incorrect': 'הססמה שסופקה אינה נכונה.',
            'too many login attempts': 'בר מדי ניסיונות התחברות.',
            'throttle': 'בר מדי ניסיונות התחברות. אנא נסה שוב ב-:seconds שניות.',
            'unauthenticated': 'לא מאומת.',
            'automation': 'אוטומציה',
            'automation settings': 'הגדרות אוטומציה',
            'automation settings (n8n)': 'הגדרות אוטומציה (n8n)',
            'add new webhook': 'הוסף webhook חדש',
            'add new webhook (n8n)': 'הוסף webhook חדש (n8n)',
            'edit webhook': 'ערוך webhook',
            'friendly name': 'שם ידידותי',
            'webhook url': 'webhook URL',
            'event type': 'סוג אירוע',
            'all events': 'כל האירועים',
            'all events (*)': 'כל האירועים (*)',
            'secret token': 'טוקן סודי',
            'secret token (optional)': 'טוקן סודי (אופציונלי)',
            'cancel': 'ביטול',
            'update bridge': 'עדכן גשר',
            'connect to n8n': 'התחבר ל-n8n',
            'active automation bridges': 'גשרי אוטומציה פעילים',
            'name': 'שם',
            'event': 'אירוע',
            'status': 'סטטוס',
            'actions': 'פעולות',
            'active': 'פעיל',
            'paused': 'מושהה',
            'recent synchronizations': 'סנכרוניזציות אחרונות',
            'time': 'זמן',
            'bridge': 'גשר',
            'response': 'תגובה',
            'webhook saved': 'webhook נשמר בהצלחה.',
            'webhook saved successfully': 'webhook נשמר בהצלחה.',
            'restaurant created': 'מסעדה נוצרה',
            'restaurant updated': 'מסעדה עודכנה',
            'hotel created': 'מלון נוצר',
            'booking created': 'הזמנה נוצרה',
            'success': 'הצלחה',
            'error': 'שגיאה',
            'warning': 'אזהרה',
            'save': 'שמור',
            'delete': 'מחק',
            'edit': 'ערוך',
            'create': 'צור',
            'update': 'עדכן',
            'add': 'הוסף',
            'close': 'סגור',
            'submit': 'שלח',
            'refresh': 'רענן',
            'loading': 'טוען...',
            'no data': 'אין נתונים',
            'email': 'דוא"ל',
            'phone': 'טלפון',
            'address': 'כתובת',
            'city': 'עיר',
            'country': 'ארץ',
            'language': 'שפה',
            'settings': 'הגדרות',
            'profile': 'פרופיל',
            'dashboard': 'לוח בקרה',
            'export': 'ייצוא',
            'import': 'ייבוא',
            'search': 'חיפוש',
            'filter': 'סנן',
            'sort': 'מיון',
            'back': 'חזור',
            'next': 'הבא',
            'previous': 'הקודם',
            'download': 'הורדה',
            'upload': 'העלאה',
        },
        'es': {
            'login': 'Iniciar sesión',
            'login successful': 'Inicio de sesión satisfactorio',
            'logout': 'Cerrar sesión',
            'logout successful': 'Cierre de sesión satisfactorio',
            'failed': 'Estas credenciales no coinciden con nuestros registros.',
            'password': 'La contraseña proporcionada es incorrecta.',
            'the provided credentials are incorrect': 'Estas credenciales no coinciden con nuestros registros.',
            'the provided password is incorrect': 'La contraseña proporcionada es incorrecta.',
            'too many login attempts': 'Demasiados intentos de inicio de sesión.',
            'throttle': 'Demasiados intentos de inicio de sesión. Por favor, inténtelo de nuevo en :seconds segundos.',
            'unauthenticated': 'No autenticado.',
            'automation': 'Automatización',
            'automation settings': 'Configuración de automatización',
            'automation settings (n8n)': 'Configuración de automatización (n8n)',
            'add new webhook': 'Agregar nuevo webhook',
            'add new webhook (n8n)': 'Agregar nuevo webhook (n8n)',
            'edit webhook': 'Editar webhook',
            'friendly name': 'Nombre descriptivo',
            'webhook url': 'URL del webhook',
            'event type': 'Tipo de evento',
            'all events': 'Todos los eventos',
            'all events (*)': 'Todos los eventos (*)',
            'secret token': 'Token secreto',
            'secret token (optional)': 'Token secreto (Opcional)',
            'cancel': 'Cancelar',
            'update bridge': 'Actualizar puente',
            'connect to n8n': 'Conectar a n8n',
            'active automation bridges': 'Puentes de automatización activos',
            'name': 'Nombre',
            'event': 'Evento',
            'status': 'Estado',
            'actions': 'Acciones',
            'active': 'Activo',
            'paused': 'Pausado',
            'recent synchronizations': 'Sincronizaciones recientes',
            'time': 'Hora',
            'bridge': 'Puente',
            'response': 'Respuesta',
            'webhook saved': 'Webhook guardado satisfactoriamente.',
            'webhook saved successfully': 'Webhook guardado satisfactoriamente.',
            'restaurant created': 'Restaurante creado',
            'restaurant updated': 'Restaurante actualizado',
            'hotel created': 'Hotel creado',
            'booking created': 'Reserva creada',
            'success': 'Éxito',
            'error': 'Error',
            'warning': 'Advertencia',
            'save': 'Guardar',
            'delete': 'Eliminar',
            'edit': 'Editar',
            'create': 'Crear',
            'update': 'Actualizar',
            'add': 'Agregar',
            'close': 'Cerrar',
            'submit': 'Enviar',
            'refresh': 'Actualizar',
            'loading': 'Cargando...',
            'no data': 'Sin datos',
            'email': 'Correo electrónico',
            'phone': 'Teléfono',
            'address': 'Dirección',
            'city': 'Ciudad',
            'country': 'País',
            'language': 'Idioma',
            'settings': 'Configuración',
            'profile': 'Perfil',
            'dashboard': 'Panel de control',
            'export': 'Exportar',
            'import': 'Importar',
            'search': 'Búsqueda',
            'filter': 'Filtrar',
            'sort': 'Ordenar',
            'back': 'Atrás',
            'next': 'Siguiente',
            'previous': 'Anterior',
            'download': 'Descargar',
            'upload': 'Cargar',
        },
    }
    
    # الحصول على القاموس الخاص باللغة
    lang_dict = translations.get(language_code, {})
    
    # البحث المباشر
    if text in lang_dict:
        return lang_dict[text]
    
    # البحث عن كلمات مشابهة (بحث جزئي)
    for en_key, tr_val in lang_dict.items():
        if en_key in text or text in en_key:
            return tr_val
    
    # إذا لم نجد ترجمة، نرجع النص الأصلي
    return en_value

def build_php_array(translations):
    """بناء ملف PHP"""
    php_content = "<?php\n\nreturn [\n"
    for key, value in sorted(translations.items()):
        if value:
            value_escaped = value.replace("'", "\\'").strip()
            php_content += f"    '{key}' => '{value_escaped}',\n"
    php_content += "];\n"
    return php_content

def main():
    print("=" * 80)
    print("✅ نظام الترجمة اليدوية الاحترافية الشامل")
    print("=" * 80)
    print()
    
    if not ENGLISH_DIR.exists():
        print(f"ERR: English directory not found: {ENGLISH_DIR}")
        return
    
    print("READ: Reading all English files...")
    english_files = {}
    total_keys = 0
    
    for filename in REQUIRED_FILES:
        filepath = ENGLISH_DIR / filename
        if filepath.exists():
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                translations = extract_php_array(content)
                english_files[filename] = translations
                total_keys += len(translations)
                print(f"  OK {filename} ({len(translations)} keys)")
    
    print(f"\nTOTAL: {total_keys} keys")
    print(f"SAVE: {OUTPUT_DIR}\n")
    
    languages = ['fr', 'de', 'it', 'ja', 'ru', 'tr', 'he', 'es']
    
    for lang_code in languages:
        print(f"TRANSLATE: {lang_code}...")
        
        lang_dir = OUTPUT_DIR / lang_code
        lang_dir.mkdir(parents=True, exist_ok=True)
        
        for filename, en_dict in english_files.items():
            translated = {}
            
            for key, value in en_dict.items():
                if value and len(value.strip()) > 0:
                    translated_text = translate_manually(value, lang_code)
                    translated[key] = translated_text
                else:
                    translated[key] = value
            
            php_content = build_php_array(translated)
            output_path = lang_dir / filename
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(php_content)
        
        print(f"  OK {lang_code}\n")
    
    print("=" * 80)
    print("SUCCESS: All translations completed!")
    print(f"LOCATION: {OUTPUT_DIR}")
    print("=" * 80)

if __name__ == '__main__':
    main()
