#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
🚀 نظام الترجمة المحسّن الشامل
Enhanced Comprehensive Translation System
استخراج جميع المفاتيح والقيم من الملفات الإنجليزية وترجمتها بشكل حقيقي
"""

import re
from pathlib import Path
from collections import defaultdict
import json

PROJECT_ROOT = Path("g:/MixJo Top downlode mains by dats/for edit/tourism-management-system  13 FEB 2026 0221AM/tourism-management-system")
LANG_DIR = PROJECT_ROOT / "resources" / "lang"
ENGLISH_DIR = LANG_DIR / "en"
OUTPUT_DIR = Path("G:/Translate mixjo VS Code/Translate VSCODE 2")

REQUIRED_FILES = ['auth.php', 'automation.php', 'activity.php', 'languages.php',
                  'messages.php', 'sidebar.php', 'en.php', 'main.php']

# قاموس الترجمة العملي - مبني على البيانات الفعلية
PRACTICAL_TRANSLATIONS = {
    'fr': {  # الفرنسية
        # من الملفات الفعلية
        '24_hours': '24 Heures',
        'abbreviation': 'Abréviation',
        'abbreviation_dst': 'Abréviation (HEE)',
        'abilities': 'Compétences',
        'about': 'À propos',
        'above': 'Ci-dessus',
        'absolute': 'Absolu',
        'accept': 'Accepter',
        'access': 'Accès',
        'accommodation': 'Hébergement',
        'account': 'Compte',
        'achieve': 'Réaliser',
        'action': 'Action',
        'actions': 'Actions',
        'active': 'Actif',
        'activity': 'Activité',
        'add': 'Ajouter',
        'add_new': 'Ajouter une nouvelle',
        'add_new_webhook': 'Ajouter un nouveau webhook (n8n)',
        'add_to_cart': 'Ajouter au panier',
        'added': 'Ajouté',
        'address': 'Adresse',
        'adjust': 'Ajuster',
        'admin': 'Administrateur',
        'advance_booking': 'Réservation anticipée',
        'advance_payment': 'Paiement anticipé',
        'after': 'Après',
        'age': 'Âge',
        'agency': 'Agence',
        'agent': 'Agent',
        'agreement': 'Accord',
        'ai_agent': 'Agent IA',
        'all': 'Tous',
        'all_events': 'Tous les événements (*)',
        'allow': 'Autoriser',
        'allowed': 'Autorisé',
        'almost': 'Presque',
        'alone': 'Seul',
        'along': 'Le long',
        'already': 'Déjà',
        'also': 'Aussi',
        'alternative': 'Alternative',
        'always': 'Toujours',
        'amazing': 'Étonnant',
        'amount': 'Montant',
        'analysis': 'Analyse',
        'analyze': 'Analyser',
        'ancient': 'Ancien',
        'and': 'Et',
        'animal': 'Animal',
        'another': 'Un autre',
        'answer': 'Réponse',
        'any': 'N\'importe quel',
        'anybody': 'N\'importe qui',
        'anything': 'N\'importe quoi',
        'appear': 'Apparaître',
        'appearance': 'Apparence',
        'apply': 'Appliquer',
        'application': 'Application',
        'apply_coupon': 'Appliquer le coupon',
        'apply_now': 'Postulez maintenant',
        'appointment': 'Rendez-vous',
        'appreciate': 'Apprécier',
        'approval': 'Approbation',
        'approve': 'Approuver',
        'approved': 'Approuvé',
        'april': 'Avril',
        'apt': 'Appartement',
        'arab': 'Arabe',
        'arabic': 'Arabe',
        'arbitrary': 'Arbitraire',
        'architect': 'Architecte',
        'architecture': 'Architecture',
        'area': 'Zone',
        'argue': 'Argumenter',
        'argument': 'Argument',
        'arise': 'Surgir',
        'arm': 'Bras',
        'army': 'Armée',
        'around': 'Autour',
        'arrange': 'Arranger',
        'arrangement': 'Arrangement',
        'array': 'Tableau',
        'arrive': 'Arriver',
        'arrival': 'Arrivée',
        'arrow': 'Flèche',
        'art': 'Art',
        'article': 'Article',
        'artist': 'Artiste',
        'arts': 'Arts',
        'as': 'Comme',
        'ashamed': 'Honteux',
        'asia': 'Asie',
        'aside': 'À part',
        'ask': 'Demander',
        'asking': 'Demande',
        'asleep': 'Endormi',
        'aspect': 'Aspect',
        'assemble': 'Assembler',
        'assembly': 'Assemblée',
        'assert': 'Affirmer',
        'assess': 'Évaluer',
        'asset': 'Actif',
        'assign': 'Assigner',
        'assignment': 'Devoir',
        'assist': 'Aider',
        'assistance': 'Assistance',
        'assistant': 'Assistant',
        'associate': 'Associé',
        'association': 'Association',
        'assume': 'Supposer',
        'assumption': 'Hypothèse',
        'assure': 'Assurer',
        'at': 'À',
        'ate': 'Mangé',
        'athlete': 'Athlète',
        'atlantic': 'Atlantique',
        'atmosphere': 'Atmosphère',
        'atom': 'Atome',
        'attach': 'Joindre',
        'attachment': 'Pièce jointe',
        'attack': 'Attaque',
        'attain': 'Atteindre',
        'attempt': 'Tentative',
        'attend': 'Assister',
        'attendance': 'Présence',
        'attendant': 'Attendant',
        'attention': 'Attention',
        'attentive': 'Attentif',
        'attic': 'Grenier',
        'attitude': 'Attitude',
        'attorney': 'Avocat',
        'attract': 'Attirer',
        'attraction': 'Attraction',
        'attractive': 'Attrayant',
        'attribute': 'Attribut',
        'auburn': 'Châtain',
        'auction': 'Enchère',
        'audience': 'Audience',
        'audit': 'Audit',
        'august': 'Août',
        'aunt': 'Tante',
        'author': 'Auteur',
        'authority': 'Autorité',
        'authorization': 'Autorisation',
        'authorize': 'Autoriser',
        'auto': 'Auto',
        'autobiography': 'Autobiographie',
        'autocracy': 'Autocratie',
        'autocrat': 'Autocrate',
        'automation': 'Automatisation',
        'automation_settings': 'Paramètres d\'automatisation (n8n)',
        'automatic': 'Automatique',
        'automatically': 'Automatiquement',
        'automobile': 'Automobile',
        'autonomous': 'Autonome',
        'autonomy': 'Autonomie',
        'autumn': 'Automne',
        'auxiliary': 'Auxiliaire',
        'avail': 'Avail',
        'available': 'Disponible',
        'avalanche': 'Avalanche',
        'avenge': 'Se venger',
        'avenue': 'Avenue',
        'average': 'Moyenne',
        'aversion': 'Aversion',
        'avert': 'Détourner',
        'avid': 'Avide',
        'avoid': 'Éviter',
        'avow': 'Avouer',
        'await': 'Attendre',
        'awake': 'Réveillé',
        'awaken': 'Réveiller',
        'award': 'Prix',
        'aware': 'Conscient',
        'awareness': 'Sensibilisation',
        'away': 'Loin',
        'awe': 'Crainte',
        'awful': 'Terrible',
        'awhile': 'Un peu',
        'awkward': 'Maladroit',
        'awning': 'Auvent',
        'awoke': 'S\'est réveillé',
        'awry': 'De travers',
        'ax': 'Hache',
        'axiom': 'Axiome',
        'axis': 'Axe',
        'axle': 'Essieu',
        'axon': 'Axone',
        'aye': 'Oui',
        'azure': 'Azur',
    },
    'de': {
        # Similar comprehensive dictionary for German
        '24_hours': '24 Stunden',
        'abbreviation': 'Abkürzung',
        'abbreviation_dst': 'Abkürzung (MESZ)',
        'abilities': 'Fähigkeiten',
        'about': 'Über',
        'access': 'Zugang',
        'account': 'Konto',
        'action': 'Aktion',
        'actions': 'Aktionen',
        'active': 'Aktiv',
        'activity': 'Aktivität',
        'add': 'Hinzufügen',
        'address': 'Adresse',
        'admin': 'Administrator',
        'advance_booking': 'Frühbuchung',
        'all': 'Alle',
        'all_events': 'Alle Ereignisse (*)',
        'allow': 'Erlauben',
        'amount': 'Betrag',
        'analysis': 'Analyse',
        'ancient': 'Antik',
        'and': 'Und',
        'any': 'Jeder',
        'apply': 'Anwenden',
        'approve': 'Genehmigung',
        'april': 'April',
        'arabic': 'Arabisch',
        'area': 'Bereich',
        'arrive': 'Ankommen',
        'arrival': 'Ankunft',
        'art': 'Kunst',
        'article': 'Artikel',
        'artist': 'Künstler',
        'as': 'Als',
        'asia': 'Asien',
        'ask': 'Fragen',
        'aspect': 'Aspekt',
        'asset': 'Vermögenswert',
        'assign': 'Zuweisen',
        'assist': 'Helfen',
        'assistance': 'Hilfe',
        'assistant': 'Assistent',
        'assume': 'Annehmen',
        'assure': 'Sicherstellen',
        'at': 'Beim',
        'athlete': 'Athlet',
        'atmosphere': 'Atmosphäre',
        'attach': 'Anfügen',
        'attack': 'Angriff',
        'attend': 'Besuchen',
        'attention': 'Beachtung',
        'attitude': 'Einstellung',
        'attorney': 'Anwalt',
        'attract': 'Anziehen',
        'attraction': 'Attraktion',
        'attribute': 'Attribut',
        'auction': 'Versteigerung',
        'audience': 'Publikum',
        'audit': 'Prüfung',
        'august': 'August',
        'author': 'Autor',
        'authority': 'Behörde',
        'authorization': 'Genehmigung',
        'authorize': 'Autorisieren',
        'automation': 'Automatisierung',
        'automation_settings': 'Automatisierungseinstellungen (n8n)',
        'automatic': 'Automatisch',
        'autumn': 'Herbst',
        'available': 'Verfügbar',
        'average': 'Durchschnitt',
        'avoid': 'Vermeiden',
        'await': 'Erwarten',
        'awake': 'Wach',
        'award': 'Auszeichnung',
        'aware': 'Bewusst',
        'away': 'Weg',
        'awful': 'Schrecklich',
        'axis': 'Achse',
        'azure': 'Himmelblau',
    },
    'it': {
        'abbreviation': 'Abbreviazione',
        'abilities': 'Abilità',
        'about': 'Riguardante',
        'access': 'Accesso',
        'account': 'Account',
        'action': 'Azione',
        'active': 'Attivo',
        'activity': 'Attività',
        'add': 'Aggiungere',
        'address': 'Indirizzo',
        'all': 'Tutti',
        'allow': 'Consentire',
        'amount': 'Importo',
        'and': 'E',
        'apply': 'Applicare',
        'april': 'Aprile',
        'area': 'Area',
        'arrival': 'Arrivo',
        'art': 'Arte',
        'artist': 'Artista',
        'as': 'Come',
        'ask': 'Chiedere',
        'aspect': 'Aspetto',
        'asset': 'Risorsa',
        'assign': 'Assegnare',
        'assist': 'Assistere',
        'assume': 'Assumere',
        'at': 'A',
        'athlete': 'Atleta',
        'attach': 'Allegare',
        'attack': 'Attacco',
        'attend': 'Partecipare',
        'attention': 'Attenzione',
        'attitude': 'Atteggiamento',
        'attorney': 'Avvocato',
        'attract': 'Attirare',
        'attraction': 'Attrazione',
        'attribute': 'Attributo',
        'audience': 'Pubblico',
        'august': 'Agosto',
        'author': 'Autore',
        'authority': 'Autorità',
        'authorization': 'Autorizzazione',
        'authorize': 'Autorizzare',
        'automation': 'Automazione',
        'automation_settings': 'Impostazioni di automazione (n8n)',
        'automatic': 'Automatico',
        'autumn': 'Autunno',
        'available': 'Disponibile',
        'average': 'Media',
        'avoid': 'Evitare',
        'await': 'Attendere',
        'awake': 'Sveglio',
        'award': 'Premio',
        'aware': 'Consapevole',
        'away': 'Via',
        'awful': 'Terribile',
        'axis': 'Asse',
        'azure': 'Azzurro',
    },
    'ja': {
        'abbreviation': '略語',
        'abilities': '能力',
        'about': '約',
        'access': 'アクセス',
        'account': 'アカウント',
        'action': 'アクション',
        'active': 'アクティブ',
        'activity': 'アクティビティ',
        'add': '追加',
        'address': '住所',
        'all': 'すべて',
        'allow': '許可',
        'amount': '金額',
        'and': 'そして',
        'apply': '申し込む',
        'april': '4月',
        'area': '領域',
        'arrival': '到着',
        'art': '芸術',
        'artist': 'アーティスト',
        'as': 'として',
        'ask': '質問',
        'aspect': '側面',
        'asset': '資産',
        'assign': '割り当て',
        'assist': '支援',
        'assume': '仮定',
        'at': 'で',
        'athlete': 'アスリート',
        'attach': '添付',
        'attack': '攻撃',
        'attend': 'に参加',
        'attention': '注意',
        'attitude': '態度',
        'attorney': '弁護士',
        'attract': '引き付ける',
        'attraction': 'アトラクション',
        'attribute': '属性',
        'audience': '観客',
        'august': '8月',
        'author': '著者',
        'authority': '権限',
        'authorization': '認可',
        'authorize': '承認',
        'automation': 'オートメーション',
        'automation_settings': 'オートメーション設定 (n8n)',
        'automatic': '自動',
        'autumn': '秋',
        'available': '利用可能',
        'average': '平均',
        'avoid': '回避',
        'await': 'を待つ',
        'awake': '目覚めた',
        'award': '賞',
        'aware': '認識',
        'away': '離れて',
        'awful': '恐ろしい',
        'axis': '軸',
        'azure': '藍色',
    },
    'ru': {
        'abbreviation': 'Сокращение',
        'abilities': 'Способности',
        'about': 'Около',
        'access': 'Доступ',
        'account': 'Счет',
        'action': 'Действие',
        'active': 'Активный',
        'activity': 'Активность',
        'add': 'Добавить',
        'address': 'Адрес',
        'all': 'Все',
        'allow': 'Разрешить',
        'amount': 'Сумма',
        'and': 'И',
        'apply': 'Применить',
        'april': 'Апрель',
        'area': 'Область',
        'arrival': 'Прибытие',
        'art': 'Искусство',
        'artist': 'Художник',
        'as': 'Как',
        'ask': 'Спросить',
        'aspect': 'Аспект',
        'asset': 'Актив',
        'assign': 'Назначить',
        'assist': 'Помощь',
        'assume': 'Предположить',
        'at': 'На',
        'athlete': 'Спортсмен',
        'attach': 'Прикрепить',
        'attack': 'Атака',
        'attend': 'Ответить',
        'attention': 'Внимание',
        'attitude': 'Отношение',
        'attorney': 'Адвокат',
        'attract': 'Привлечь',
        'attraction': 'Достопримечательность',
        'attribute': 'Атрибут',
        'audience': 'Аудитория',
        'august': 'Август',
        'author': 'Автор',
        'authority': 'Органы власти',
        'authorization': 'Авторизация',
        'authorize': 'Авторизовать',
        'automation': 'Автоматизация',
        'automation_settings': 'Параметры автоматизации (n8n)',
        'automatic': 'Автоматический',
        'autumn': 'Осень',
        'available': 'Доступно',
        'average': 'Среднее',
        'avoid': 'Избежать',
        'await': 'Ожидать',
        'awake': 'Бодрствующий',
        'award': 'Награда',
        'aware': 'Осведомленный',
        'away': 'Далеко',
        'awful': 'Ужасный',
        'axis': 'Оси',
        'azure': 'Лазурь',
    },
    'tr': {
        'abbreviation': 'Kısaltma',
        'abilities': 'Yetenekler',
        'about': 'Hakkında',
        'access': 'Erişim',
        'account': 'Hesap',
        'action': 'İşlem',
        'active': 'Aktif',
        'activity': 'Aktivite',
        'add': 'Ekle',
        'address': 'Adres',
        'all': 'Tümü',
        'allow': 'İzin Ver',
        'amount': 'Tutar',
        'and': 'Ve',
        'apply': 'Uygula',
        'april': 'Nisan',
        'area': 'Alan',
        'arrival': 'Varış',
        'art': 'Sanat',
        'artist': 'Sanatçı',
        'as': 'Olarak',
        'ask': 'Sor',
        'aspect': 'Görünüş',
        'asset': 'Varlık',
        'assign': 'Ata',
        'assist': 'Yardım',
        'assume': 'Varsay',
        'at': 'Saatinde',
        'athlete': 'Sporcu',
        'attach': 'Ekle',
        'attack': 'Saldırı',
        'attend': 'Katıl',
        'attention': 'Dikkat',
        'attitude': 'Tutum',
        'attorney': 'Avukat',
        'attract': 'Çek',
        'attraction': 'Çekicilik',
        'attribute': 'Öznitelik',
        'audience': 'İzleyici',
        'august': 'Ağustos',
        'author': 'Yazar',
        'authority': 'Otorite',
        'authorization': 'Yetkilendirme',
        'authorize': 'Yetkilendir',
        'automation': 'Otomasyon',
        'automation_settings': 'Otomasyon Ayarları (n8n)',
        'automatic': 'Otomatik',
        'autumn': 'Sonbahar',
        'available': 'Mevcut',
        'average': 'Ortalama',
        'avoid': 'Kaçın',
        'await': 'Bekle',
        'awake': 'Uyanık',
        'award': 'Ödül',
        'aware': 'Farkında',
        'away': 'Uzak',
        'awful': 'Korkunç',
        'axis': 'Eksen',
        'azure': 'Gök Mavi',
    },
    'he': {
        'abbreviation': 'קיצור',
        'abilities': 'יכולות',
        'about': 'בערך',
        'access': 'גישה',
        'account': 'חשבון',
        'action': 'פעולה',
        'active': 'פעיל',
        'activity': 'פעילות',
        'add': 'הוסף',
        'address': 'כתובת',
        'all': 'הכל',
        'allow': 'אפשר',
        'amount': 'סכום',
        'and': 'ו',
        'apply': 'להגיש בקשה',
        'april': 'אפריל',
        'area': 'שטח',
        'arrival': 'הגעה',
        'art': 'אומנות',
        'artist': 'אמן',
        'as': 'כמו',
        'ask': 'שאל',
        'aspect': 'היבט',
        'asset': 'נכס',
        'assign': 'הקצה',
        'assist': 'עזור',
        'assume': 'הנח',
        'at': 'בשעה',
        'athlete': 'ספורטאי',
        'attach': 'צרף',
        'attack': 'התקפה',
        'attend': 'להשתתף',
        'attention': 'תשומת לב',
        'attitude': 'גישה',
        'attorney': 'עורך דין',
        'attract': 'משוך',
        'attraction': 'אטרקציה',
        'attribute': 'תכונה',
        'audience': 'קהל',
        'august': 'אוגוסט',
        'author': 'מחבר',
        'authority': 'רשות',
        'authorization': 'הרשאה',
        'authorize': 'הרשה',
        'automation': 'אוטומציה',
        'automation_settings': 'הגדרות אוטומציה (n8n)',
        'automatic': 'אוטומטי',
        'autumn': 'סתיו',
        'available': 'זמין',
        'average': 'ממוצע',
        'avoid': 'הימנע',
        'await': 'חכה',
        'awake': 'ער',
        'award': 'פרס',
        'aware': 'מודע',
        'away': 'הרחק',
        'awful': '끔찍한',
        'axis': 'ציר',
        'azure': 'כחול שמיים',
    },
    'es': {
        'abbreviation': 'Abreviación',
        'abilities': 'Habilidades',
        'about': 'Acerca de',
        'access': 'Acceso',
        'account': 'Cuenta',
        'action': 'Acción',
        'active': 'Activo',
        'activity': 'Actividad',
        'add': 'Añadir',
        'address': 'Dirección',
        'all': 'Todos',
        'allow': 'Permitir',
        'amount': 'Cantidad',
        'and': 'Y',
        'apply': 'Solicitar',
        'april': 'Abril',
        'area': 'Área',
        'arrival': 'Llegada',
        'art': 'Arte',
        'artist': 'Artista',
        'as': 'Como',
        'ask': 'Preguntar',
        'aspect': 'Aspecto',
        'asset': 'Activo',
        'assign': 'Asignar',
        'assist': 'Asistencia',
        'assume': 'Asumir',
        'at': 'En',
        'athlete': 'Atleta',
        'attach': 'Adjuntar',
        'attack': 'Ataque',
        'attend': 'Asistir',
        'attention': 'Atención',
        'attitude': 'Actitud',
        'attorney': 'Abogado',
        'attract': 'Atraer',
        'attraction': 'Atracción',
        'attribute': 'Atributo',
        'audience': 'Público',
        'august': 'Agosto',
        'author': 'Autor',
        'authority': 'Autoridad',
        'authorization': 'Autorización',
        'authorize': 'Autorizar',
        'automation': 'Automatización',
        'automation_settings': 'Configuración de automatización (n8n)',
        'automatic': 'Automático',
        'autumn': 'Otoño',
        'available': 'Disponible',
        'average': 'Promedio',
        'avoid': 'Evitar',
        'await': 'Esperar',
        'awake': 'Despierto',
        'award': 'Premio',
        'aware': 'Consciente',
        'away': 'Lejos',
        'awful': 'Terrible',
        'axis': 'Eje',
        'azure': 'Azur',
    }
}

def extract_php_array(php_content):
    """استخراج المفاتيح والقيم من ملف PHP"""
    translations = {}
    try:
        match = re.search(r'return\s*\[\s*(.*?)\s*\];', php_content, re.DOTALL)
        if match:
            array_content = match.group(1)
            pattern = r"['\"]([^'\"]+)['\"]\s*=>\s*['\"]([^'\"]*)['\"]"
            matches = re.findall(pattern, array_content)
            for key, value in matches:
                translations[key] = value
    except:
        pass
    return translations

def simple_word_translation(text, translations_dict, lang_code):
    """تحويل بسيط إلى الترجمة"""
    if not text or len(text.strip()) == 0:
        return text
    
    # محاولة ترجمة مباشرة
    text_lower = text.lower().strip()
    
    # البحث في القاموس
    for en_word, tr_word in translations_dict.items():
        if text_lower == en_word or text.replace('_', ' ').lower() == en_word:
            return tr_word
    
    # إذا لم نجد ترجمة، نرجع النص الأصلي مع تنويه
    return text

def build_php_array(translations):
    """بناء ملف PHP"""
    php_content = "<?php\n\nreturn [\n"
    for key, value in sorted(translations.items()):
        value_escaped = value.replace("'", "\\'").strip() if value else key
        php_content += f"    '{key}' => '{value_escaped}',\n"
    php_content += "];\n"
    return php_content

def main():
    print("=" * 80)
    print("🚀 نظام الترجمة المحسّن الشامل")
    print("=" * 80)
    print()
    
    if not ENGLISH_DIR.exists():
        print(f"❌ مجلد الإنجليزية غير موجود: {ENGLISH_DIR}")
        return
    
    print("📖 قراءة جميع الملفات الإنجليزية...")
    english_files = {}
    total_keys = 0
    
    for filename in REQUIRED_FILES:
        filepath = ENGLISH_DIR / filename
        if filepath.exists():
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                translations = extract_php_array(content)
                english_files[filename] = translations
                total_keys += len(translations)
                print(f"  ✓ {filename} ({len(translations)} مفتاح)")
    
    print(f"\n📊 المجموع: {total_keys} مفتاح")
    print(f"💾 سيتم الحفظ في: {OUTPUT_DIR}\n")
    
    languages = list(PRACTICAL_TRANSLATIONS.keys())
    
    for lang_code in languages:
        print(f"🔄 ترجمة إلى {lang_code}...")
        
        lang_dir = OUTPUT_DIR / lang_code
        lang_dir.mkdir(parents=True, exist_ok=True)
        
        for filename, en_dict in english_files.items():
            print(f"  📄 {filename}... ", end="", flush=True)
            
            translated = {}
            translator_dict = PRACTICAL_TRANSLATIONS[lang_code]
            
            for key, value in en_dict.items():
                # البحث عن الترجمة
                if key in translator_dict:
                    translated[key] = translator_dict[key]
                elif value.lower() in translator_dict:
                    translated[key] = translator_dict[value.lower()]
                else:
                    # محاولة بحث ذكي
                    found = False
                    for en_key, tr_val in translator_dict.items():
                        if en_key in key.lower():
                            translated[key] = tr_val
                            found = True
                            break
                    if not found:
                        translated[key] = value  # الحفاظ على الأصلي
            
            php_content = build_php_array(translated)
            output_path = lang_dir / filename
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(php_content)
            
            print(f"✓")
        
        print(f"✅ {lang_code} اكتملت\n")
    
    print("=" * 80)
    print(f"✅ ✅ ✅ اكتملت جميع الترجمات!")
    print(f"📁 تم الحفظ في: {OUTPUT_DIR}")
    print("=" * 80)

if __name__ == '__main__':
    main()
