@extends('layouts.auth')

@section('title', 'Two-Factor Authentication')

@push('styles')
    <style>
        .branded-bg {
            background-image: url('{{ asset('metronic/media/images/2600x1600/1.png') }}');
        }

        .dark .branded-bg {
            background-image: url('{{ asset('metronic/media/images/2600x1600/1-dark.png') }}');
        }
    </style>
@endpush

@section('content')
    <!--begin::Authentication - 2FA -->
    <div class="grid lg:grid-cols-12 grow min-h-[100svh]">

        {{-- Left: Form (60% on desktop) --}}
        <div class="flex justify-center items-center p-8 lg:p-10 order-2 lg:order-1 lg:col-span-7">
            <div class="kt-card max-w-[380px] w-full">

                {{-- Authenticator Code form --}}
                <form action="{{ route('two-factor.login') }}" class="kt-card-content flex flex-col gap-5 p-10"
                    id="sign_in_form" method="post">
                    @csrf

                    <div class="flex justify-center">
                        <img alt="2FA" class="dark:hidden h-20 mb-2"
                            src="{{ asset('metronic/media/illustrations/34.svg') }}" />
                        <img alt="2FA" class="light:hidden h-20 mb-2"
                            src="{{ asset('metronic/media/illustrations/34-dark.svg') }}" />
                    </div>

                    <div class="text-center mb-2">
                        <h3 class="text-lg font-medium text-mono mb-2">Verify your Identity</h3>
                        <span class="text-sm text-secondary-foreground">
                            Enter the verification code generated by your authenticator app
                        </span>
                    </div>

                    @if ($errors->any())
                        <div class="text-sm font-medium text-danger text-center -mb-2">
                            {{ __('The provided two factor authentication code was invalid.') }}
                        </div>
                    @endif

                    <div class="flex flex-col gap-1">
                        <input class="kt-input text-center h-[50px] text-lg tracking-[0.2em]" name="code"
                            placeholder="X X X X X X" type="text" inputmode="numeric" autofocus
                            autocomplete="one-time-code" />
                    </div>

                    <button class="kt-btn kt-btn-primary flex justify-center grow mt-2" type="submit">
                        Continue
                    </button>

                    <div class="flex items-center justify-center mt-2">
                        <a class="text-2sm text-primary font-medium hover:text-primary-active" href="#"
                            onclick="event.preventDefault();
                                     document.getElementById('sign_in_form').classList.add('hidden');
                                     document.getElementById('recovery_form').classList.remove('hidden');">
                            Use Recovery Code instead
                        </a>
                    </div>
                </form>

                {{-- Recovery Code form (hidden by default) --}}
                <form action="{{ route('two-factor.login') }}" class="kt-card-content flex flex-col gap-5 p-10 hidden"
                    id="recovery_form" method="post">
                    @csrf

                    <div class="flex justify-center">
                        <img alt="recovery" class="dark:hidden h-20 mb-2"
                            src="{{ asset('metronic/media/illustrations/32.svg') }}" />
                        <img alt="recovery" class="light:hidden h-20 mb-2"
                            src="{{ asset('metronic/media/illustrations/32-dark.svg') }}" />
                    </div>

                    <div class="text-center mb-2">
                        <h3 class="text-lg font-medium text-mono mb-2">Recovery Code</h3>
                        <span class="text-sm text-secondary-foreground">
                            Enter one of your emergency recovery codes
                        </span>
                    </div>

                    <div class="flex flex-col gap-1">
                        <input class="kt-input text-center h-[50px] tracking-widest" name="recovery_code"
                            placeholder="XXXXXXXX-XXXXXXXX" type="text" autocomplete="off" />
                    </div>

                    <button class="kt-btn kt-btn-primary flex justify-center grow mt-2" type="submit">
                        Submit Recovery Code
                    </button>

                    <div class="flex items-center justify-center mt-2">
                        <a class="text-2sm text-primary font-medium hover:text-primary-active" href="#"
                            onclick="event.preventDefault();
                                     document.getElementById('recovery_form').classList.add('hidden');
                                     document.getElementById('sign_in_form').classList.remove('hidden');">
                            Back to Authenticator Code
                        </a>
                    </div>
                </form>

            </div>
        </div>

        {{-- Right: Branded background image (40% on desktop) --}}
        <div class="hidden lg:block lg:order-2 lg:col-span-5 bg-center xl:bg-cover bg-no-repeat branded-bg">
            <div class="flex flex-col p-8 lg:p-16 gap-6 text-center">
                <a href="{{ url('/') }}" class="mb-5 flex justify-center">
                    <img class="dark:hidden max-w-none" src="{{ asset('metronic/media/app/mixjo-default-logo-dark.svg') }}"
                        style="height: 100px !important; min-height: 100px !important; width: auto !important; object-fit: contain !important;" />
                    <img class="hidden dark:block max-w-none"
                        src="{{ asset('metronic/media/app/mixjo-default-logo.svg') }}"
                        style="height: 100px !important; min-height: 100px !important; width: auto !important; object-fit: contain !important;" />
                </a>
                <div class="flex flex-col gap-4">
                    <div class="flex flex-col gap-2">
                        <h3 class="text-2xl font-semibold text-mono">Welcome to MixJo.</h3>
                        <div class="text-base font-medium text-secondary-foreground">
                            Everything you need to optimise and grow your travel business in one solution.
                        </div>
                    </div>
                    <div class="text-base font-medium text-secondary-foreground">
                        Travel CRM + backoffice + booking engine software tailored for travel agents, tour operators,
                        homeworkers and DMC's.
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--end::Authentication - 2FA-->
@endsection
